### ISSUE TITLE
Moving windows to other desktops return client to original one if a new client is added.

### ISSUE THREAD

**Issue by annata83** [lingtjien/Grid-Tiling-Kwin#10]
Hey LinG;  one thing I notice is that when you move a window to another virtual desktop if you open another client the windows you previously move returns to the original desktop; for example, client A original desktop is 1, so I move it to desktop 2, in desktop 2 I open a client B and then client A returns to desktop 1 and so on for any client for any desktop.. in other words an X client has to stay on the same desktop in order to maintan position if you want to open another cleint with that  X client in particular.
if you open X client and leave it in the same Desktop tilling behavior works just fine.
You think that will be possible to attain tilling after mover X client to any other desktop if any other client is added?

**Comment by lingtjien** [comment]
If I understand your question correctly...

The behavior the script (should) have/has:
If you have a client open on virtual desktop 2 and try to open another client on the same virtual desktop it should keep the original client on this virtual desktop and try to add the new client to this virtual desktop, if there is not enough "space" on this virtual desktop for the new client then it will start looking for a virtual desktop which does have enough "space" for the new client starting from virtual desktop 1.

You say that the client is moved back to the previous desktop when you add a new client to the same virtual desktop. This should not happen... (and it doesn't happen during my testing)

I'm expecting that you use the default kwin shortcuts to move clients between virtual desktops... Do you use the global shortcuts: "Grid-Tiling: Move *direction* Desktop" to move the clients or "Window one *direction*"? The default kwin shortcuts to move clients do not work properly to move clients between virtual desktops

**Comment by annata83** [comment]
Hi again Ling; thanks for asking for clarification; first let me say that the tilling behavior on any virtual desktop works great, but I found that when I move any x client to any other virtual desktop (but for this example lets say VD2"Virtual Desktop 2")then if I open any other client on VD2 it will send back the previously move x client to it original VD.in other words, If a move any client to any other virtual desktop then that client will not stay there if another clint is open in the same VD it will return back to it original one.
To move clients I use what I think is the default kwin global shortcut which is called "switch to Desktop".
If I use the Grid-Tilling: Move*Direction* ShortCut tilling works Great and there is no problem of relocating to the previous desktop.
The Reason I am trying to use Kwin Switch To desktop is because I can use a .1 to X number of VD to move any client to any number I want instead of only the default  left-right-up-down provided with the Grid-tilling move Your script comes with. I am so used to I3 that it got just stock into my way of using VD's. 
All that being said; thanks for the reply, I now understand that the kwin shortcut does not work as you mention and will find a way to reorganize my workflow with the Grid-tilling option.

**Comment by lingtjien** [comment]
I like the idea of having global shortcuts to move clients to a specific desktop, added it to my To-Do list

**Comment by lingtjien** [comment]
To-Do: Remove "grid-tiling: move client desktop" and support the default KWin shortcuts to move clients between virtual desktops

**Comment by DanitiKain** [comment]
Awesome to see this being worked on.  I think with this for me its almost complete tool.  I will post a new topic for enhancement that I think would make this thing pretty complete.

**Comment by lingtjien** [comment]
Feature added in dev branch, soon merge to master after I do some more testing.
