### ISSUE TITLE
Value is undefined and could not be converted to an object

### ISSUE THREAD

**Issue by madjoe** [lingtjien/Grid-Tiling-Kwin#100]
During shutdown I've noticed the following error in my journal log file:

```
kwin_x11[1577]: file:///home/me/.local/share/kwin/scripts/grid-tiling/contents/code/Main.qml:30: TypeError: Value is undefined and could not be converted to an object
```

`Main.qml:30` (function _disconnectRemove_):
```
obj[prop].disconnect(obj[prop + saveName]);
```

**Comment by lingtjien** [comment]
Interesting, a few questions:
1. If you have `kwin_x11` running (to see the logging) and enable and disable the script. Do you also get this error?
  - open terminal
  - `kwin_x11 --replace &`
  - open kwin script module in the system settings
  - enable and disable the script (with applications open, etc...)
  - can you reproduce it this way?
2. What applications do you have running when you shutdown your system?
3. Does it also happen when you shutdown all applications on your desktop manually before shutting down the system?

(I use a volatile system journal (memory based and wiped on reboot), so a bit hard for me to observe this)

**Comment by madjoe** [comment]
> * open terminal
> * `kwin_x11 --replace &`
> * open kwin script module in the system settings
> * enable and disable the script (with applications open, etc...)
> * can you reproduce it this way?

To do. Output: https://pastebin.com/raw/xbhZCJPY

> 1. What applications do you have running when you shutdown your system?

https://pastebin.com/raw/zB7hV5Uy

> 2. Does it also happen when you shutdown all applications on your desktop manually before shutting down the system?

I always close all running apps (windows) before shutting down, therefore this issue is strictly related to that condition.

**Comment by lingtjien** [comment]
I don't follow you...

> During shutdown I've noticed the following error in my journal log file:

and

> When I tested it with a proper shutdown, I couldn't reproduce the issue:

and

> I always close all running apps (windows) before shutting down, therefore this issue is strictly related to that condition.

So during what kind of shutdown does it happen then?

**Comment by madjoe** [comment]
I couldn't reproduce the issue after following your steps. Maybe it was due to `kwin_x11` restart?

It happened each time before I ran that command.

**Comment by lingtjien** [comment]
So which steps do you perform in order to create this error?

1. start computer
2. login
3. shutdown
4. error???

**Comment by madjoe** [comment]
journal log (A):
```
$ journalctl -b -1 | grep -A999 "System is rebooting.\|System is powering down." | grep tiling
```

1. start computer
2. login
3. shutdown
4. start computer
5. login
6. the above command line (A) returned:

```
kwin_x11[1577]: file:///home/me/.local/share/kwin/scripts/grid-tiling/contents/code/Main.qml:30: TypeError: Value is undefined and could not be converted to an object
```
7. open terminal > `kwin_x11 --replace &`
8. shutdown
9. start computer
10. login
11. the above command line (A) returned empty string (no error messages relater to your script)

Ever since I ran step 7 I can not reproduce the error mentioned in step 6 again.

**Comment by lingtjien** [comment]
Have you been able to reproduce it lately? (kinda hard to fix something if you can't reproduce it anymore)

**Comment by madjoe** [comment]
No, I didn't encounter the issue again. If/when it happens, I'll post it here.
