### ISSUE TITLE
Some apps not being ignored!

### ISSUE THREAD

**Issue by AadityaThapaAce** [lingtjien/Grid-Tiling-Kwin#101]
Apps like thunderbird and bitwarden are not being ignored. I have added them to the ignore list.

[https://imgur.com/mwsBXbr](url) 

Also, please add rounded corners and also make a ignore list for rounded corners app if you can make it.
Thank you...!

**Comment by lingtjien** [comment]
Did you reboot after changing the setting? (setting are only loaded in **once** the script is started)

Rounded corners are part of the borders, there are plenty of KDE plasma themes that provide rounded corners, if that is something you desire. But this script only deals with movement/placement of windows and I'd like to keep it this way (Unix philosphy, do one thing and do it good)

So if you want rounded borders, you have to turn on borders (either permanenetly in the settings or manually using the shortcut) and then you need a theme that supports rounded corners for the borders (afterwards you can also decrease the size of the borders in the KWin settings, but that's not part of this script, this script only deals with borders being active or not, not the styling of these borders)

**Comment by migmolrod** [comment]
Tip: instead of rebooting, for me it also works disabling the script, click apply, then enabling the script and click apply again. Script seems to get reloaded with new settings, that way.
