### ISSUE TITLE
Can you set a border around focused tile?

### ISSUE THREAD

**Issue by Reactified** [lingtjien/Grid-Tiling-Kwin#105]
It is somewhat hard to tell what tile I am currently focused on, and the standard KDE window borders are hidden for tiles.
Is there some other way to get a border around the window that currently has focus?

**Comment by lingtjien** [comment]
Currently you can't but I don't see why I couldn't add it

**Comment by lingtjien** [comment]
Try the dev branch, it's optional and can be turned on in the configuration UI

**Comment by lingtjien** [comment]
has been merged into master. If you stumble upon any issues you can open a new ticket 😄
