### ISSUE TITLE
Can't install

### ISSUE THREAD

**Issue by StormsRider** [lingtjien/Grid-Tiling-Kwin#106]
```
kpackagetool5 --type KWin/Script -i https://github.com/lingtjien/Grid-Tiling-Kwin.git
```
Error: Installation of failed: No such file:

Thanks for the most confusing installation instructions I've ever seen!!!!!!!!!

**Comment by lingtjien** [comment]
You're supposed to check out the repository first, perhaps it's a good idea to read a little about git and how it works.

(Side note, this is open source, so for most of us here it's our hobby and we ain't getting paid for this work. You're not entitled to my help or any of us in the community. So if you're going in with a bad attitude, then expect very little help.)
