### ISSUE TITLE
Move Next Desktop/Screen not working properly when using 3 monitors

### ISSUE THREAD

**Issue by tran-simon** [lingtjien/Grid-Tiling-Kwin#108]
Hi,

When using 3 monitors, for 2 of them it works fine. On my leftmost monitor, when I try to move to the next screen, it will change virtual desktops instead. I also can't go from my middle screen to the left screen.

Furthermore, it would be great to have a shortcut to only move to the next screen (and do nothing if it's the last screen or wrap around to the first screen)

thank you

**Comment by lingtjien** [comment]
The `Grid-Tiling: Move Next Desktop/Screen` (and previous) shortcuts prioritize screens over virtual desktops. So for example assuming you have 3 screens, 1, 2 and 3.

If you try to move a client on virtual desktop 1 and screen 1 to the next using this shortcut, then it should try to move to screen 2 virtual desktop 1, then screen 3 virtual desktop 1 and then screen 1 virtual desktop 2 (and then the same for the reverse process).

So I'm assuming your left most monitor is assigned screen 3.

For more fine control you can use the default KWin shortcuts `Window One Desktop to the *Left/Right*` and `Window to *Next/Previous* Screen`. The latter one should be the one you're looking for

**Comment by tran-simon** [comment]
"Window to *Next/Previous* Screen" doesn't work, since when I try to resize the window after changing its screen, it will snap back to the original screen. I feel like Grid-Tiling remembers that a window is on screen 1, and when you move it to screen 2 with the KWin shortcut, it doesn't tell grid-tiling that the screen has changed, so when grid-tiling updates it snaps back the window to screen 1

Also, is there a reason why simply dragging a window to a second screen doesn't seem to work? seems like this should be the simplest way, since you can already drag windows around to tile them

**Comment by lingtjien** [comment]
> "Window to Next/Previous Screen" doesn't work, since when I try to resize the window after changing its screen, it will snap back to the original screen. I feel like Grid-Tiling remembers that a window is on screen 1, and when you move it to screen 2 with the KWin shortcut, it doesn't tell grid-tiling that the screen has changed, so when grid-tiling updates it snaps back the window to screen 1

Which version are you on? There was a bug in an older version where screen changing didn't work

**Comment by tran-simon** [comment]
Updated grid-tiling and now moving windows with the mouse seems to work and it's enough for my workflow. Thanks a lot for your quick replies

**Comment by lingtjien** [comment]
You have the default KWin shortcuts `Window to *Next/Previous* Screen` for that. There are also `Window to Screen *Number*` shortcuts which KWin provides by default, which should give you more fine control.

But screens don't have a grid in KWin. It's just a list from front to back and the screens are labeled as such: 0, 1, 2, 3, etc... So there isn't really any grid to them, it's just a list, so there isn't a sensible approach to moving them up/down
