### ISSUE TITLE
How to open new windows maximized?

### ISSUE THREAD

**Issue by jiriks74** [lingtjien/Grid-Tiling-Kwin#109]
Is there an option to maximize every window, or is there just one way of tiling?

**Comment by lingtjien** [comment]
You mean one tile per virtual desktop?

**Comment by jiriks74** [comment]
> You mean one tile per virtual desktop?

I mean that I have multiple windows tiled and I want to have all the windows maximized

**Comment by lingtjien** [comment]
So let's say you have 4 tiles on a virtual desktop and you want a way to maximize them all at the same time, so that they are all on top of each other?

**Comment by jiriks74** [comment]
> So let's say you have 4 tiles on a virtual desktop and you want a way to maximize them all at the same time, so that they are all on top of each other?

Exactly. Sorry for the delay. I'll close this because pull request with this feature has been issued [here](https://github.com/lingtjien/Grid-Tiling-Kwin/pull/111)
