### ISSUE TITLE
Missing minimize/maximize/close buttons on window title

### ISSUE THREAD

**Issue by kolbaba** [lingtjien/Grid-Tiling-Kwin#112]
When running Grid-Tiling-Kwin the min/max/close icons disappear. Is this intended behavior or a bug?
![image](https://user-images.githubusercontent.com/3298804/116720314-a5b71500-a9a1-11eb-8f89-c4c4b28a9592.png)

**Comment by lingtjien** [comment]
By default the borders are hidden, you can use the UI to adjust that setting or the global shortcut `Grid-Tiling: Toggle Border`

**Comment by kolbaba** [comment]
@lingtjien wow, I feel dumb now. Working as expected, thanks!
