### ISSUE TITLE
Windows won't tile on Wayland

### ISSUE THREAD

**Issue by acidrums4** [lingtjien/Grid-Tiling-Kwin#114]
From Plasma 5.21 onwards, grid-tiling-kwin won't tile windows on Wayland. A single window in an empty virtual desktop will show up maximised (and respecting the set gaps), but a second window opened in the same virtual desktop also will show up maximised, over the first window.

Some keyboard shortcuts won't work, like the 'refresh' keyboard shortcut or the 'toggle gaps', but others do - like the 'tile/float' one.

Grid-tiling-kwin was working as expected with Wayland on Plasma 5.20.

**Comment by lingtjien** [comment]
Which branch are you using and are you up to date?

KWin 5.21 broke a part of the scripting API, so I added the necessary changed to fix that. They should have been merged back into master. #99

**Comment by acidrums4** [comment]
I'm using the master branch, and yes, it's up to date. I was aware of #99 - grid-tiling-kwin ain't breaking the wayland session, it just don't tile any windows > 1.

**Comment by lingtjien** [comment]
Oh yeah I didn't formulate that ticket very well, but in 5.21 there was a change in the KWin API which broke this tiling script (but only for wayland). 

But I'm guessing you have a different problem then, but the problem sounds like the same one as in #99

So first things first, to confirm that you have the latest version and also installed it correctly. Can you tell me contents on line `28` in `~/.local/share/kwin/scripts/grid-tiling/contents/code/Manager.qml` (it should say something with `client.internalId` and not `client.windowId`)

After that could you reset your settings to default and then proceed with the following steps

1. unplug secondary displays
2. reboot
3. start 1 instance of konsole
4. start an new instance of konsole
5. does it tile the second konsole next to the first one?
