### ISSUE TITLE
Confusing config

### ISSUE THREAD

**Issue by pasqui23** [lingtjien/Grid-Tiling-Kwin#115]
![image](https://user-images.githubusercontent.com/6931743/129378629-0dd39de0-30a0-46d0-957b-1668685919b0.png)
What does Rows and columns mean?
Why the default is a list of 2?
While the other two tabs in the config are acceptable, this one is not.

**Comment by lingtjien** [comment]
How many rows and columns (the size of the grid) you want per virtual desktop separated by a comma. Every input field under each other is for a different screen. Defaults to 2 rows and 2 columns for every virtual desktop and every screen.

I agree that the way to input this setting this way is not optimal. But I haven't found a different qt widget yet that allows for a more user friendly way to input these settings.

**Comment by pasqui23** [comment]
> How many rows and columns (the size of the grid) you want per virtual desktop separated by a comma. Every input field under each other is for a different screen. Defaults to 2 rows and 2 columns for every virtual desktop and every screen.
> 
> For example if you have 2 screens connected to your computer and you want the first virtual desktop to be `2x2` and the second virtual desktop to be `3x3` on screen 1, but you want a `4x4` for the first virtual desktop and a `5x5` for the second virtual desktop on screen 2. Then you would supply the following settings:
> 
> `2, 3, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2` `2, 3, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2` `4, 5, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2` `4, 5, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2`
> 
> I agree that the way to input this setting this way is not optimal. But I haven't found a different qt widget yet that allows for a more user friendly way to input these settings.

At least put the description in the tab window

**Comment by lingtjien** [comment]
Added tooltips to the various input fields with explanation
