### ISSUE TITLE
Add keybind switch to three coloumns

### ISSUE THREAD

**Issue by TegarOk** [lingtjien/Grid-Tiling-Kwin#116]
Its really hard to get 1 row & 3 coloums configuration.
The default configuration was 2 rows & 2 coloumns, if i set  2R & 3C the rows will be filled first instead coloumns, so its really hard to get 3 coloumns at first.

**Comment by lingtjien** [comment]
If you want 1x3 then why do you set it 2x3 why not 1x3?

**Comment by TegarOk** [comment]
Sometimes i need 2 rows.
And i dont want to switch my configuration everytime.

**Comment by lingtjien** [comment]
So if I understand you correctly, you prefer to fill all the columns first before we start a new row?

with 2x3 (2 rows, 3 columns)
```
1
```
```
1 2
```
```
1 2 3
```
```
1 2 3
4
```
```
1 2 3
4 5
```
```
1 2 3
4 5 6
```

**Comment by TegarOk** [comment]
> So if I understand you correctly, you prefer to fill all the columns first before we start a new row as in the following example?
Yes.

**Comment by lingtjien** [comment]
Added to other task #89
