### ISSUE TITLE
Keyboard shortcuts don't work

### ISSUE THREAD

**Issue by madjoe** [lingtjien/Grid-Tiling-Kwin#117]
Hi! I just updated my system, including your script and suddenly all of my shortcuts work except for `Grid-Tiling-Kwin`. I tried to reconfigure some keys, same outcome. I also tried resetting the settings to default, nothing changed. Any ideas what could it be? Thanks.

**Comment by madjoe** [comment]
It seems assigning `Meta+'` to any action breaks the KWin shortcuts AND/OR changing the naming from "Decrease Step" to "Decrease Size" breaks it.

**Comment by lingtjien** [comment]
Unfortunately that's not something I can fix. Once a script registers shortcuts they stay there until you manually remove them. So if I rename shortcuts in a newer version then you'll stil have the shortcuts assigned to the old ones.

To fix this you need to disable the KWin script and go to the shortcuts settings and there press the delete button on the KWin application that contains the shortcuts. Once you start the script again it will register the new shortcuts.

I also wrote a small section about this in the README.md but I'll expand a bit further on that for clarity purposes
