### ISSUE TITLE
How to make windows remember to stay floating or tiled?

### ISSUE THREAD

**Issue by tran-simon** [lingtjien/Grid-Tiling-Kwin#118]
Could there be a new shortcut or something to add a window to the list of windows that should always float, instead of having to tweak the settings for every popup that should be floating?

thanks

**Comment by lingtjien** [comment]
There is a shortcut to temporary make a client float and tile (depending on it's current state) `Grid-Tiling: Tile/Float` (default assigned to `Meta+T`)

**Comment by tran-simon** [comment]
I'm looking for a way to persist the state, so that next time the application start it will remember to float.

It is annoying to `Meta+T` everytime a popup appears

**Comment by lingtjien** [comment]
So if I understand you correctly, you want to be able to change the config settings using a shortcut?

**Comment by tran-simon** [comment]
yes

**Comment by lingtjien** [comment]
Well, that one has a simple answer. Not possible through the KWin API as far as I'm aware (currently) so even if I wanted to, I can't implement it. Persistent settings have to be set through the UI

**Comment by tran-simon** [comment]
thanks
