### ISSUE TITLE
Ability to invert layout

### ISSUE THREAD

**Issue by rejedai** [lingtjien/Grid-Tiling-Kwin#120]
By default, a new window opens in the lower left corner, hence the main and largest one is always on the right. Is there a way to invert the layout so that a new window opens on the left?

**Comment by lingtjien** [comment]
I don't follow your question

Assume we start with the following setup

```
1
```

and we open 3 more windows (2, 3 and 4)

we end up with 
```
1 2
3 4
```

What is the behavior that you want?

**Comment by lingtjien** [comment]
Assuming #89 would provide the feature you desire
