### ISSUE TITLE
Wayland: qt windows do not get tiled

### ISSUE THREAD

**Issue by pasqui23** [lingtjien/Grid-Tiling-Kwin#121]
On plasma wayland 5.23.3 the tiled status of qt windows (and only qt windoes) keep being toggled off, even after I manually toggle it on with Super+T .

**Comment by lingtjien** [comment]
I am running wayland with plasma version 5.23.3 and I haven't had any problems yet.

Do you have a minimal example (from startup) that reproduces the issue you speak of?

**Comment by lingtjien** [comment]
https://github.com/lingtjien/Grid-Tiling-Kwin/issues/123
