### ISSUE TITLE
Remove gap if single window

### ISSUE THREAD

**Issue by volitank** [lingtjien/Grid-Tiling-Kwin#123]
Is it possible to remove the gap if the window is the only one on the screen? For example on my second monitor I usually only have Firefox. I would like there not to be a gap if this is the case.

Additionally how difficult would it be to add containers similar to i3? I like your script but am really missing tabbed containers.

**Comment by lingtjien** [comment]
Gaps are system wide, so you either have them or you don't. But if you only have 1 client on that second monitor then you can float the window first `Grid-Tiling: Tile/Float (Meta+T)` and then you can do whatever you want with that window without it getting tiled. So you can just maximize it then

**Comment by lingtjien** [comment]
I've never used any tiling WM (including i3) so I don't know what you mean by containers.

**Comment by volitank** [comment]
A container in i3 is basically just like a grouping of windows. I guess kind of like a workspace but you can move it around. So you could have like 4 windows in a container and switch it to tabbed mode. It looks kind of like one window but you can cycle through the tabs. Probably not trivial to implement, especially if you're not familiar with it.

**Comment by lingtjien** [comment]
Sounds like a complex piece to implement, while I don't think it fits in well within the KWin structure. Have you ever used activities in KWin, perhaps that accomplishes almost the same goal as you describe, you can also tab through activities and their idea is to also group certain applications.

**Comment by volitank** [comment]
I haven't, I'll check it out. Anything is going to be a big adjustment for me. I've been using i3 with KDE for quite a while, but I'd like to switch native kwin if I can. Just have to find a way that doesn't disrupt my workflow too much

On the topic of the gap, would it be too much to implement a check so if the client is the only one in the workspace You could remove it for that workspace? You said that it is system wide, so I'm guessing it might be unfeasible to implement.

I tried looking at the code to see if I could maybe patch it but 1. I only know python and 2. have no idea how to manage windows lol

**Comment by lingtjien** [comment]
My goal has never been to imitate other WM's or implement all their features. I just make features and implement whatever I think makes sense in my own workflow (or suggested by others that I think make sense). I think that if you want all the features of a certain WM then one should use that WM and not try to mimic it. Seems a bit inefficient to mimic a piece of software that's already freely available 😄 

May I ask, why you want to switch away from KDE + i3 to bare KDE with KWin?

KWin comes with a lot of different features, so if you're going to change from i3 to KWin, you might as well take this opportunity to see what is all available, you may be surprised by a feature that could end up really useful. But that's completely up to you of course.

It's technically possible to implement, but it would become a bit messy to do. I'll see if I can make a hack patch for you but I don't think I'll implement it into the project itself.

**Comment by volitank** [comment]
Nicer integration with KDE. Things are a little buggy sometimes using this combination, and since i3 doesn't composite then I have to use picom. Also i3 and picom don't work on wayland, so I would have to use sway, which means my transparent windows can't have blur. Just using kwin the experience is very similar between both X and wayland.

I figured it might not be as easy as a patching one file, thanks for trying though. It's not too much of a hassle just to maximize the window.

Another thing that I do like about your script is being able to move and resize windows with the mouse. One downside of i3.

I will still continue using your script and see what features could fit my workflow or even improve upon it.
