### ISSUE TITLE
Games are tiled when launched

### ISSUE THREAD

**Issue by ShabirK21** [lingtjien/Grid-Tiling-Kwin#124]
How can i stop tiling on games that i launch, i tried adding steam to be ignored, but that only stops the steam client to be ignored for tiling but the games launched are still tiled.

**Comment by lingtjien** [comment]
You need to explicitly add the games as well. WM can't really distinguish between games and regular applications (as far as I'm aware)

**Comment by ShabirK21** [comment]
So if I need to add multiple games individually? I tried adding just steam but that didn't prevent the games launches through steam from tiling

**Comment by lingtjien** [comment]
Yes, in the ignored name section, you can expand the regex with the names of all the applications that you don't want to tile. In your case that would be the games that you play

**Comment by ShabirK21** [comment]
Alright, thanks!
