### ISSUE TITLE
Adjusting the sizing logic after swapping position

### ISSUE THREAD

**Issue by jazz-it** [lingtjien/Grid-Tiling-Kwin#125]
Say we have tiling windows A and B, positioned left and right respectively. If we place focus on the window B and increase its size, B size will be increased and A will be decreased. Now let's try to swap positions of A and B and try to place focus on the window A (which is now on the right) and try to increase its size - the sizing logic will be reversed, even though you gave an instruction to INCREASE the window A at the new position, its size will be DECREASED instead and vice versa.

**Comment by lingtjien** [comment]
I think you didn't focus A correctly after you swapped A and B

1. Open 2 konsole windows 
```
1 2
```
2. increase size of `1` with shortcut
3. swap to new position
```
2 1
```
4. focus 1 (make sure `1` is focused by typing something and seeing that text is being input into konsole 1)
5. increase size of `1`

**Comment by jazz-it** [comment]
Hm... you're right.
The issue was in step 4: even though I kept moving my mouse pointer over `1`, it was still not focused - I had to click on it, but I usually don't have to, since my mouse pointer is set to give focus on a hovering window. It seems that doesn't work right after swapping window positions.
