### ISSUE TITLE
Windows are no longer tiled after changing screen configuration

### ISSUE THREAD

**Issue by andigandi** [lingtjien/Grid-Tiling-Kwin#127]
As the title says, windows are no longer tiled, if the screen configuration changes. I have one monitor that I can not leave connected to my PC all the time. When I unplug or replug it, as soon as my screen configuration changes, the script no longer tiles any windows that already existed. It appears as if the script can no longer control them. Refreshing (Meta+R), Toggle Tile (Mega+Umschalt+T) or Tile/Float (Meta+T) hotkeys have no effect on these windows. Restarting the script (Uncheck it in Kwin-Scripts, apply, re-check it, apply) also has no effect. Newly opened windows act like expected, but they ignore the previously existing ones with their tiling.
Is there anything more, that I can provide to help fix the issue?

Arch Linux
kwin 5.23.5
Xorg Server 21.1.3
Grid-Tiling-Kwin commit: 851a0cdcd5f4022863aa68d4bafa69b504845f09

**Comment by lingtjien** [comment]
> Restarting the script (Uncheck it in Kwin-Scripts, apply, re-check it, apply) also has no effect

And rebooting does fix it?

**Comment by andigandi** [comment]
Rebooting does indeed fix. Were you able to reproduce this? I mean, this seems like there is a difference between a fresh KWin start and restarting the script...

**Comment by lingtjien** [comment]
I don't really have access to a multimonitor setup, but I added a new global shortcut that does a hard internal `Reset`. Give that one a try and see if it works after you connect/disconnect monitors. If that works I can always try to make it automatic later on

**Comment by lingtjien** [comment]
due to plasma 6 release, and big changes to the API. I will close all old inactive tickets, if you still encounter problems then feel free to create a new ticket
