### ISSUE TITLE
kwin-script-grid-tiling.desktop

### ISSUE THREAD

**Issue by jazz-it** [lingtjien/Grid-Tiling-Kwin#129]
Hi,

I re-installed the script manually by following the [Local Installation (Advanced)](https://github.com/lingtjien/Grid-Tiling-Kwin#local-installation-advanced) instructions and I ended up with `kwin-script-grid-tiling.desktop` not existing in `~/.local/share/kservices5/`. I hope that's the expected behavior? If not, how do I recreate it? Thanks.

**Comment by lingtjien** [comment]
That is correct, with the new changes in KWin this old hack is no longer required in order to get the settings dialog. So as long as you still have the dialog that allows you to adjust settings then everything is alright.

**Comment by jazz-it** [comment]
Perfect, thank you!
