### ISSUE TITLE
[Suggestion] keep the repo size minimal

### ISSUE THREAD

**Issue by georgem3** [lingtjien/Grid-Tiling-Kwin#13]
I think it's unnecessarily big. Maybe host the previews on other sites i.e. Imgur?

**Comment by lingtjien** [comment]
yeah true, the gifs are already hosted on another site but the main video is too large so that's why it's still in the repo. 

Do you know if it's possible to remove the whole preview folder from the repository and its history?

**Comment by lingtjien** [comment]
There ya go, that should do it. Went from 120M to 12M. I even had it on my todo list but I forgot about it... Thanks for the reminder
