### ISSUE TITLE
Grid tiling does not tile 

### ISSUE THREAD

**Issue by pasqui23** [lingtjien/Grid-Tiling-Kwin#130]
I have installed Grid Tiling but not all apps are tiled and even those that are often lose their tiling status and I have to manually reenable tiling.

**Comment by lingtjien** [comment]
You're going to have to provide a bit more information.

- X11 or Wayland?
- Does Meta+R work to tile clients again?
- When do windows lose their tiling?
- How did you install the script and enable it?

**Comment by lingtjien** [comment]
I'm going to assume you've found the problem. If not then please create a new ticket (with a minimal working example in a clean environment to reproduce)
