### ISSUE TITLE
Ignore list documentation

### ISSUE THREAD

**Issue by vhsch** [lingtjien/Grid-Tiling-Kwin#132]
There are no examples or documentation on how the Ignored should be written.
Do I use quotation marks? regex? commas or semicolons? 
Just a few lines in the README would be sufficient.

**Comment by lingtjien** [comment]
I agree, I'll add it to the documentation.

Did you figure it out btw and this only a feature request to update the documentation or do you need help to write the ignore?

**Comment by lingtjien** [comment]
done
