### ISSUE TITLE
please document more on ignore

### ISSUE THREAD

**Issue by zxx-457** [lingtjien/Grid-Tiling-Kwin#134]
I am confused by how to ignore window

what does name and caption stand for ? 

And how to seperate the value to have muiltple ignores ?

It would be great to have some examples.

Why not using class and instance to match the window?

**Comment by lingtjien** [comment]
Agreed, I had already updated it in the dev branch, I merged it to master now. If there are still things unclear then let me know :)

*FYI Updating to the new version will cause you to lose your settings*
