### ISSUE TITLE
cannot support Multi-Activities windows

### ISSUE THREAD

**Issue by Louis-J** [lingtjien/Grid-Tiling-Kwin#135]
if a window shows in more than one kwin-activities, and the window numbers are different between the same virtual desktop across activities.

reproduce:
window a: shows in activity 1 and virtual desktop 1
window b: shows in activity 1, 2 and virtual desktop 1

then the window b can only have half-screen size in activity2.

**Comment by lingtjien** [comment]
Let's first discuss what the intended behavior is that you expect.

As far as I can see one window can not be tiled correctly in two different activities, so I believe if a window is active in more than 1 activity it should float (which I think that is how I implemented it but maybe that's broken). Let's start with an example, where `A` (a terminal for example) and `B` (a web browser) are two different applications and you decide that you want the web browser to be active in both activity 1 and 2.

```
Activity 1

A B

Activity 2

B

```

I think, `B` should fully occupy the whole virtual desktop (taking into account gaps) for activity 2, but only take up the right half in activity 1. So I don't think there is a correct geometry to apply here to B.

What behavior were you expecting?

**Comment by lingtjien** [comment]
due to plasma 6 release, and big changes to the API. I will close all old inactive tickets, if you still encounter problems then feel free to create a new ticket
