### ISSUE TITLE
New window of the same application doesn't tile.

### ISSUE THREAD

**Issue by tran-simon** [lingtjien/Grid-Tiling-Kwin#136]
Hi

My chrome and konsole windows tile fine, but when I use CTRL+N to open a new window, the new window doesn't tile.

I'm on master, I have multiple monitors

thanks

**Comment by lingtjien** [comment]
Are you sure you installed the correct version? I am on the dev branch and `New Window` in konsole creates a new tiled window for me

**Comment by lingtjien** [comment]
due to plasma 6 release, and big changes to the API. I will close all old inactive tickets, if you still encounter problems then feel free to create a new ticket
