### ISSUE TITLE
Can't ignore Tor browser without affecting other programs

### ISSUE THREAD

**Issue by nailerNAS** [lingtjien/Grid-Tiling-Kwin#138]
Can't make just the Tor browser being ignored. Played with different expressions, the only one that works is just 'tor' but it also makes Firefox and qBittorrent ignored. Other expressions I've tried:

\btor\b
\stor\s
^tor$
tor browser
tor\sbrowser
tor.browser

**Comment by lingtjien** [comment]
What is the `Window class (application)` property of the tor window and of the others that you don't want to match?

> You can find the value for these properties on a window by opening the Windows Operations Menu (there is a global shortcut for this)

**Comment by nailerNAS** [comment]
Tor browser: "navigator tor browser"

Firefox: "navigator firefoxdeveloperedition"
qBittorrent: "qbittorrent"

**Comment by lingtjien** [comment]
Hmm that's weird, `tor browser` should have worked then or you could go even further and do a match on the full string so `navigator tor browser`. Have you reloaded the script after you changed settings? 

(section from readme)
> When you adjust the settings in the menu, this script needs to be restarted before the settings are applied. You can do this by turning the script off, apply, turn it back on and apply again or a complete KWin restart (re-log/reboot).

**Comment by lingtjien** [comment]
Hmm weird, then could you add the following `print(client.resourceName)` in `contents/code/Manager.qml` between line `7` and `8`. And also replace line `10` with the following 3 lines
```
let t = client.transient || !client.normalWindow || (config.blacklist && config.blacklist.test(client.resourceName));
print(t);
return t;
```
Then check the logging to see what is being printed when you open the 3 different applications?

**Comment by lingtjien** [comment]
for x11 you can use the same command but replace kwin_wayland with x11 so
```
journalctl -f _COMM=kwin_x11
```
the logging should start with kwin_x11[<pid>]: qml: <message>

It's easiest to first open a terminal and run the command and then try to open the other applications and see what the logging prints

**Comment by lingtjien** [comment]
due to plasma 6 release, and big changes to the API. I will close all old inactive tickets, if you still encounter problems then feel free to create a new ticket
