### ISSUE TITLE
RFE: Shortcut Key for Opening Next Windows Horizontal or Vertical

### ISSUE THREAD

**Issue by DanitiKain** [lingtjien/Grid-Tiling-Kwin#14]
I played around with i3wm a bit and one thing that I found very useful was the ability to decide how the next window should open.  So if you wanted the next window to open vertical you hit meta+o as an exmple and it would open the next application vertically. Then if you wanted to open horizontal you hit meta+e and the next app would open horizontal. This has some advantages in that you can decide how the next app should open depending what you are going to be doing.

**Comment by lingtjien** [comment]
With the current data structure that won't be possible as the data is ordered in columns and not rows, thus clients are always vertical. This would require a lot of rewriting, maybe in the future but not any time soon...
