### ISSUE TITLE
Can't tile after most recent update

### ISSUE THREAD

**Issue by jazz-it** [lingtjien/Grid-Tiling-Kwin#141]
I use local installation, Plasma version: 5.27.11
Since the last update, I've noticed:
```
"X-Plasma-API-Minimum-Version": "6.0"
```
Does it mean currently the Plasma 5.x is no longer supported? If not, I already set all the settings to default, rebooted and still can't get it to work.

**Comment by lingtjien** [comment]
The current master is still for plasma 5, only the development branch is plasma 6 compatible. Plasma 5 and Plasma 6 are not compatible with each other so I had to make a big rewrite.

I made a branch for Plasma 5 called `<6.0` so just stick with that branch if you run plasma 5. Master will also soon be updated to Plasma 6

**Comment by jazz-it** [comment]
That explains it, thanks:

```
$ git rev-parse --abbrev-ref HEAD
develop
```
