### ISSUE TITLE
Firefox window doesn't resize properly

### ISSUE THREAD

**Issue by djneba** [lingtjien/Grid-Tiling-Kwin#146]
Firefox (librewolf) remembers it's window size when closing. Upon reopening it, tiles ok, but it doesn't resize the window to fit the tile. Instead, the window size is the same as before it was closed. If the window is minimized and restored, then it tiles properly.

**Comment by lingtjien** [comment]
so to specify, you used the following steps:

1. open 1 terminal
2. open firefox on same virtual desktop (and screen)
3. you observe the terminal being properly tiled to the left half?
4. what happens to firefox?

**Comment by djneba** [comment]
Yes the terminal is properly tiled. Firefox's top left corner goes to the correct place next to the terminal window, but Firefox keeps it's previous size, too big if it was the only window when previously closed, or too small if it was quarter tiled previously. If I minimize and restore, or resize manually, the Firefox window then resizes itself to the correct size.

**Comment by lingtjien** [comment]
sounds like a timing issue, what happens if you increase the `delay` in the config? (from `10` to `100` and `1000`)

And does using the refresh shortcut also work to fix it instead of a minimize or resize?

**Comment by djneba** [comment]
I think I found out what the problem was. The value of "privacy.resistFingerprinting" in about:config Firefox settings, needs to be set to "true". So, it's not directly related to the tiling script. It works as expected now.
