### ISSUE TITLE
RFE: Create New Virtual Desktop

### ISSUE THREAD

**Issue by DanitiKain** [lingtjien/Grid-Tiling-Kwin#15]
Shortcut Key to create New Virtual Desktop + One to Create New and Send Current Active Window to it would be nice as well.

**Comment by lingtjien** [comment]
This would first require proper support for dynamic virtual desktops as the script would have to manage virtual desktops too or at least handle the signals that are triggered when changing the number of virtual desktops. I like the idea but it's still far away.

**Comment by lingtjien** [comment]
For now I think it's best if I leave virtual desktop control out of this script, since it seems that there are already other scripts that do this.
