### ISSUE TITLE
the README file needs correction

### ISSUE THREAD

**Issue by chhui3** [lingtjien/Grid-Tiling-Kwin#16]
In the README.md, for the local installation part, 
`mkdir -p ~/.local/share/kservices5`and
`ln -s ../kwin/scripts/grid-tiling/metadata.desktop kwin-script-grid-tiling.desktop `
there should be 
`cd ~/.local/share/kservices5` in between

**Comment by hhhorb** [comment]
Confirmed, I was trying this and wound up with a broken link.

**Comment by lingtjien** [comment]
fixed in dev branch soon merged to master. Thanks for the report, forgot to add that line while I was rewriting the readme some time ago...
