### ISSUE TITLE
Not really an *issue* but need some help with keybindings

### ISSUE THREAD

**Issue by BrianD91** [lingtjien/Grid-Tiling-Kwin#17]
Im fairly new to KDE in general, I'm not sure how to setup the resizing of the windows and could use some help, lol

**Comment by lingtjien** [comment]
You still want help? :P

**Comment by lingtjien** [comment]
By default, chromium is set to have a minSpace value of 2, which means that it can never become smaller than half your screen. So assuming you use a 2x2 grid then if you open 1 terminal and then chromium you would still have 0.25 space in the first column but your second column would be filled with chromium (0.5). So if you then open another terminal it will occupy that last 0.25 space in the first column. If you then open a third terminal it will be moved to a new virtual desktop as the first one is now filled by 2 terminals (2x0.25) plus 1 chromium (0.5) = 1. Similarly clients with a minSpace value of 1 will always take up a whole virtual desktop.

The second gif in the readme and the description above it describes this behavior

**Comment by BrianD91** [comment]
hhmmmmm, maybe I'm misunderstanding then. I'd like a 4x4 grid. In the Client Min Space in the Grid-Tiling --System Settings I have everything set to 8, I thought that would make it work?

**Comment by BrianD91** [comment]
I swear I had it working last night, but now it doesn't want to cooperate. 

So I want a total of 16 possible cells, I want everything to be able to be as small as ONE of those cells. 

So I set:
>Row: 4, 4
>Column: 4, 4
>Client Min Space: everything set to 16


that should work, right?

**Comment by BrianD91** [comment]
I think it might just be my browser. I'm using Eloston's Ungoogled-Chromium, it doesn't seem to want to behave properly. But my other browsers (Falkon and Iridium) both work great! I'll just switch to using Iridium as my primary browser, there's very minimal differnce between the two in terms of privacy so it's not a major setback to me. Thanks for the help and other than the issue I had, I really do like the script! great work!

**Comment by lingtjien** [comment]
You can also empty the list of minSpace, it defaults to 16 when you want a 4x4 grid
