### ISSUE TITLE
What happened to this script?

### ISSUE THREAD

**Issue by DanitiKain** [lingtjien/Grid-Tiling-Kwin#18]
Just wondering why it is no longer available for download.

**Comment by lingtjien** [comment]
to download from where?

**Comment by DanitiKain** [comment]
From KDE store.. The file has been removed and can no longer be downloaded. Trying to find out..

**Comment by lingtjien** [comment]
I've never put the file there myself (and I wouldn't even know how), I've only ever linked to this repository. So I don't know how it was available for download in the store or how to put it there, but if you know how then I'm willing to give it a try if it isn't too cumbersome.

**Comment by rayvermey** [comment]
Hi, is it possible to open a program/application directly fullscreen instead of have it tiled?
Thank you.
Ray

**Comment by lingtjien** [comment]
Hmm seems the script is in the kde.store under the kwin scripts section so.... I don't know what else to do on that front...

> Hi, is it possible to open a program/application directly fullscreen instead of have it tiled?
> Thank you.
> Ray

1. You have to ignore that client or start it off as floating (depending on what you prefer) this way the script will not change the geometry of the client when it is launched.
2. Then you can use any other means to start it off as fullscreen, I believe KWin rules allow you to specify such things.

Also please open a ticket if you have new unrelated questions
