### ISSUE TITLE
Add an option to disable windows transparency

### ISSUE THREAD

**Issue by rominf** [lingtjien/Grid-Tiling-Kwin#23]

**Comment by lingtjien** [comment]
what do you mean by "disable"?

Currently, the noOpacity toggle in the UI determines the initial state of transparency. If you put it on, it won't make any windows transparent (unless you toggle it yourself with the global shortcut).

**Comment by rominf** [comment]
Thank you for the response, @lingtjien.
Here is how my screen looks like after enabling the extension:
![screenshot](https://user-images.githubusercontent.com/3449635/47605530-6abe7a00-da10-11e8-8a83-c567074786ed.png)
I want my windows to be without transparency again.
And I don't see any GUI for configuring the extension settings.

**Comment by lingtjien** [comment]
By default the script sets the transparency to 10%. If you use the global shortcut called `Grid-Tiling: Toggle Opacity` it should make your windows non transparent. If you want to change the default to be not transparent you can open the UI and activate the `No Opacity` toggle.

**Comment by rominf** [comment]
> If you use the global shortcut called Grid-Tiling: Toggle Opacity (Meta+O, by default) it should make your windows non transparent.

Thank you. Nice to know.

> you can open the UI

Where is it?

**Comment by lingtjien** [comment]
In your screenshot you have the script highlighted in blue (in the left window), inside the blue on the right side you see two icons. The info button and the settings icon opens the settings UI for this script.

**Comment by rominf** [comment]
Thank you, @lingtjien, strange how I missed it :(

**Comment by seqizz** [comment]
![image](https://user-images.githubusercontent.com/307899/50588301-b9a9e500-0e81-11e9-894d-33c750c720ed.png)
I can't see the configure button sadly

**Comment by seqizz** [comment]
Aaah nevermind I failed to symlink it :man_facepalming: Now it's here
