### ISSUE TITLE
Row/Column Setting Not Working

### ISSUE THREAD

**Issue by Wolfereign** [lingtjien/Grid-Tiling-Kwin#25]
I'm trying to change the grid size to be 3 Columns by 2 Rows.  But I cannot get the script to do anything but 2x2.  I have 3 virtual desktops on a single 34inch UltraWide screen.

![screenshot_20181117_193739](https://user-images.githubusercontent.com/5723368/48668015-9b8a5000-eaa0-11e8-870b-7ab33cf70b0f.png)

**Comment by Wolfereign** [comment]
So disabling and re-enabling the script got the third column working but the columns get filled really weird.  It fills a 2x2 grid before putting anything in the third column.  How do I get it to fill the first 3 columns before putting anything in the second row?

**Comment by lingtjien** [comment]
> So disabling and re-enabling the script got the third column working

To apply any settings that you make in the UI you have to re-enable the script or relog (or reboot). This is not something I can control. This applies to all KWin scripts as far as I'm aware (I also put this in the readme).

> I have 3 virtual desktops on a single 34inch UltraWide screen

The values in the UI for row and column that you supplied (in this case 2,2,2 x 3,3,3) apply for different **physical screens**. This script does not support using different grid sizes per virtual desktop. For example, if you have 2 monitors by default (2,2 x 2,3) the script will create 2x2 grids for all virtual desktops on your first monitor and 2x3 grids for all your virtual desktops on your second monitor.

> How do I get it to fill the first 3 columns before putting anything in the second row?

That is currently not supported. The script always tries to keep the grid as square as possible when adding new clients. 

Motivation for why I implemented it this way: I feel that if you use a large grid for example then if it would always fill up your columns (or rows) first then you would initially end up with a lot of long rectangular shapes, which personally for me is undesirable. Most applications that I know place their toolbars around the sides (top, left, right, bottom) for example. If you would then give the application the size of their toolbar then the actual "canvas" of the application would be minimal. Imagine an application with a top toolbar (such as a text editor) in a 3x1 grid (3 rows, 1 column) for example.

**Comment by Wolfereign** [comment]
Thanks for the clarification!
