### ISSUE TITLE
How to move clients between cols/rows?

### ISSUE THREAD

**Issue by jarradh** [lingtjien/Grid-Tiling-Kwin#26]
I can't seem to find in README or shortcuts, when I open a new application it is opening the window under another, what I'm finding myself having to do is close windows, swap two windows then launch. Not a big deal but it'd be nice not to have to restore state in application when I mess up

**Comment by lingtjien** [comment]
- Moving (not switching) between columns still needs to be implemented see #11. 

That would be if you have a setup like this:
```
1 2
3 4
```
and you want to achieve this
```
1 4
3 4
2 4
```
with a new shortcut called `Grid-Tiling: Move Left` in this example on `2`

- How do you foresee moving between rows?

if we take the same example with the same initial condition
```
1 2
3 4
```
what is your desired result with moving and not switching client between rows? Currently `Grid-Tiling: Switch Down` already does this when used on `1`
```
3 2
1 4
```

**Comment by lingtjien** [comment]
should be implemented now in master
