### ISSUE TITLE
Does not work with plasma 5.14.4 ?

### ISSUE THREAD

**Issue by murphytalk** [lingtjien/Grid-Tiling-Kwin#27]
I followed the installation procedure and can even see it being listed when run `plasmapkg2 -t kwinscript -l`, nevertheless after re-login to KDE it cannot be found in system global key bindings ...

**Comment by lingtjien** [comment]
You mean you can't find the shortcuts but the script is installed or the script is not installed at all?

If you installed the script correctly then it should show up in System Settings -> Window Management -> KWin scripts

The shortcuts should be in the global shortcuts menu in the section `Kwin` here you can do a search on `grid-tiling` for example

**Comment by murphytalk** [comment]
Oh, yes , found it there , apparently I was looking for it in wrong place. It's neat , thanks !
