### ISSUE TITLE
Multiple Screens Behavior

### ISSUE THREAD

**Issue by Nano-Ocelot** [lingtjien/Grid-Tiling-Kwin#28]
I've noticed a few bugs and strange behaviors when it comes to having multiple physical screens.
1. The KWIN shortcut 'Window to Next/Previous Screen' doesn't behave nicely with the script. If you move a window to another screen with the shortcut it will snap back to it's original spot whenever another window is opened, or the screen is refreshed, or you attempt to move the window manually again with the mouse, etc. It also has tons of visual bugs that don't get fixed with a 'refresh'. 
2. The included shortcut 'Grid-Tiling: Move Next/Previous Desktop/Screen' will move the window in a way that it will stay put, however it doesn't work well when using multiple rows of desktops. It will skip a desktop sometimes when cycling the window through them. It will also skip screens sometimes when cycling through them, likely because my secondary monitor is set to be extended to the left. You can replicate this problem by making a 2x2 grid of desktops. And 'extend left' for your second monitor. Then try to cycle through them and it will behave erratically.

As it stands, working with multiple monitors is a serious pain. The quickest and easiest workaround I've found is to switch the window to 'float', move it to the other screen, then switch it back to 'tile'. Otherwise the script has been amazing. This is with the 'master' branch by the way.

**Comment by lingtjien** [comment]
Could you try this again, I think my latest commits should have fixed it

**Comment by Nano-Ocelot** [comment]
It's definitely fixed now. Thanks for your hard work
