### ISSUE TITLE
Start window in floating mode

### ISSUE THREAD

**Issue by victorbrca** [lingtjien/Grid-Tiling-Kwin#29]
Not really an issue, but I was wondering if there's a way to start an application in floating mode? Not to be confused with 'ignored clients' or 'ignored captions'. 

It would be nice to be able to start a terminal in floating mode and add the tiling only if needed. 

Btw, nice going with the project. This is amazing!

**Comment by lingtjien** [comment]
Currently not, ignored currently means that the script ignores them completely, this has a negative side effect that the shortcuts `Grid-Tiling: Move *Next/Previous* Desktop/Screen` do not work on them.

I'm leaning more towards removing the ignored list and moving all ignored clients into the floating list by default, this would mean that you have no more clients that are always ignored by the script but that clients that you specify to ignore start out in the floating list and you can move them between the tiled and floating lists using the shortcuts.

**Comment by victorbrca** [comment]
That sounds like a great idea! Looking forward to it. 

And thanks for the quick reply.

**Comment by lingtjien** [comment]
While trying to implement it I realized that I can't get rid of the ignored list as the background of a virtual desktop are accessible too for example and it breaks a lot if you try to move those around so... I just went with your initial suggestion of adding a list of clients and captions that you can use to specify them to start as floating. (Oh and I realized that the current floating list never got cleanup, so fixed that too)

You can give it a try in the dev branch

**Comment by victorbrca** [comment]
Sorry for taking so long to test this. It works perfectly! Thank you so much for the change.

**Comment by lingtjien** [comment]
Has been merged to master, I'll probably reorder the UI a bit. It's starting to become a bit elongated.
