### ISSUE TITLE
Increase number of windows allowed on a desktop

### ISSUE THREAD

**Issue by rr1610** [lingtjien/Grid-Tiling-Kwin#30]
Is there a way to increase the maximum number of windows allowed on a desktop to more than 4? Not visible windows, but total windows? If I have 4 windows open (even if theyre minimised) and I attempt to open another, it is placed on a new desktop. Can I allow more than 4 windows (including minimised ones) on a desktop at once?

**Comment by lingtjien** [comment]
That is supplied in the `Grid Sizes` section of the settings window, by the number of rows and columns. By default, this is set to 2 rows and 2 columns for your first screen which gives you a total of 2x2=4 clients per desktop.

**Comment by rr1610** [comment]
> That is supplied in the `Grid Sizes` section of the settings window, by the number of rows and columns. By default, this is set to 2 rows and 2 columns for your first screen which gives you a total of 2x2=4 clients per desktop.

Thanks. Should have seen this myself.
