### ISSUE TITLE
change docs to use kpackagetool5

### ISSUE THREAD

**Issue by davidedmundson** [lingtjien/Grid-Tiling-Kwin#31]
Plasmapkg is deprecated. 

Should hopefully fix the need for the extra symlink too.

**Comment by lingtjien** [comment]
cool I'll check it out when I have some time

**Comment by lingtjien** [comment]
I tried kpackagetool5 but it doesn't create the file needed in kservices5 to make the user able to access the UI. When I started plasmapkg2 on my machine it was already a link to kpackagetool5 apparently.

I did change the description and replaced plasmapkg2 for kpackagetool5 but unfortunately, you still have to manually create the link. (I did report this issue a long time ago under plasmapkg2, maybe I should move that ticket in Bugzilla to kpackagetool5)
