### ISSUE TITLE
Compatibility?

### ISSUE THREAD

**Issue by SunnyBTC** [lingtjien/Grid-Tiling-Kwin#32]
HI,

Apologies for a beginner question but I'm running linux mint 19.1 cinnamon. Will this app work on there? I'm assuming it's KDE only, but I can only hope! Looks incredible and exactly what i'm after

Thanks
Sunny

**Comment by lingtjien** [comment]
It's a KWin script so it requires that you use KWin as your window manager. I'm not sure what cinnamon uses for its window manager but if it's KWin, this script should work with it fine.
