### ISSUE TITLE
system settings (and some others) bugged when started

### ISSUE THREAD

**Issue by andr813c** [lingtjien/Grid-Tiling-Kwin#33]
https://imgur.com/a/6UksYhy

I dont know exactly why this happens, but whenever i open the system settings (through the alt+space menu) it opens like this, simply moving it or doing a reload will fix it.

**Comment by lingtjien** [comment]
I also listed this in the **Useful to know** section in the readme but I didn't give an explanation there so I suppose you'd like to know why this happens.

KWin API only allows telling applications what to do but it does not allow enforcing it. In my personal opinion, a window manager should be able to enforce the settings you apply to the window to create a consistent experience across all applications for the user, but the others do not agree with my point of view. I quote from the maintainer *The window manager just tells the window "please take this geometry". The window is allowed to just change it back* here https://bugs.kde.org/show_bug.cgi?id=386021

This means that I can only use the API to tell a window "please take this geometry"  but if the window actually does so or not is not possible with the current API. This means that some stubborn applications (such as system settings) need to be told multiple times to take on a geometry.

This is why I made the global `refresh` shortcut to allow the user to tell all clients to take on their geometry again.

**Comment by madjoe** [comment]
Wow... I've been hit with this issue several times and planned to report it as an issue, but now I've just learnt the issue has much deeper roots in my desktop environment (KDE). Very frustrating and not consistent. 

E.g. sometimes I open a new window of Crhomium in Workspace 1 - it opens in a fullscreen, which is expected. Then I want to open another Chromium window and it will split my Workspace 1 in two columns of the same width and now I have two Chromium windows. Brilliant!

But sometimes (like today), I repeat exactly the same steps and there is no way I can force my Workspace 1 to split in two. It just doesn't happen. Opening a new Chrome window will always open it in a new Workspace, there is no way I can add anything to Workspace 1.

Sometimes the same confusing behavior appears for the very last Workspace (4).

**Comment by madjoe** [comment]
I think I know why this happens. Well, it's more a bug with the Rambox, Viber app and similar. Those apps always reside as windows in the background (minimized in a system tray). Sometimes a window (or a desktop) manager puts them on Workspace 1, sometimes 2, 3 or 4... etc. When it happens, since they are minimized and you don't see them, the desktop environment doesn't want to force adding another window in a workspace that is already "full", therefore you may face such behavior from my previous comment.
