### ISSUE TITLE
Toggling full screen / tiling

### ISSUE THREAD

**Issue by teonnik** [lingtjien/Grid-Tiling-Kwin#38]
Thanks for the amazing work! I really like the script.

At the moment, there is support for maximization and minimization in your script but they use different key bindings. Is it possible to use the same key binding to toggle minimization / maximization (similar to i3 Mod+f).

Similarly, toggling between tiling and floating with the same key would be really useful!

**Comment by lingtjien** [comment]
(I've never used i3, so examples and features from i3 I have no clue about)

> Similarly, toggling between tiling and floating with the same key would be really useful!

I like that suggestion, based on if the window is floating or tiling the same global shortcut can be used to change that state to the opposite.

> At the moment, there is support for maximization and minimization in your script but they use different key bindings. Is it possible to use the same key binding to toggle minimization / maximization (similar to i3 Mod+f).

Are you referring to the global shortcuts `Grid-Tiling: Maximize` and `Grid-Tiling: Unminimize Desktop`?

**Comment by teonnik** [comment]
I am referring to `Grid-Tiling: Maximize` and the `Grid-Tiling: Minimize` versions, not the desktop once. It would be really useful to have an option, e.g. `Grid-Tiling: Toggle Full Screen` which does what the `Maximize/Minimize` options do separately at the moment.

**Comment by lingtjien** [comment]
I implemented it (and cleaned up some code while I was at it), you can give it a try in the develop branch to see if the behavior is what you expect. (It's probably easiest if you remove all the global shortcuts in the KWin module (the minus button) before you apply the new version)

**Comment by madjoe** [comment]
Is there a way to avoid to backup/restore Global Shortcuts somehow, or at least to avoid doing it manually? It's kind of a drag to go through such process every time we install a new version of the script.
