### ISSUE TITLE
Issue with tiling qtcreator's child window

### ISSUE THREAD

**Issue by teonnik** [lingtjien/Grid-Tiling-Kwin#39]
In qt creator a new window can be spawned with Ctrl+E+4. That new window can't be tiled, it only floats.

**Comment by lingtjien** [comment]
My first guess would be that that window is not a "normal" window, but I'll have to look into it.

The script currently ignores all windows of types: `dialog` and `specialWindow`. I think dialog speaks for itself and quoting the documentation of KWin: `specialWindow: Returns whether the window is any of special windows types (desktop, dock, splash, ...), i.e. window types that usually don't have a window frame and the user does not use window management (moving, raising,...) on them`

**Comment by lingtjien** [comment]
I just tested it with my qt-creator (had to assign a different shortcut since `Ctrl+E, 4` didn't work) and it worked fine for me, it would create a new window and that window would be tiled immediately on the next virtual desktop (I have creator in my list of `minSpace 1` ). Which version of Qt creator do you use?

My version:
Qt Creator 4.9.1
Based on Qt 5.12.3 (GCC 8.3.0, 64 bit)

**Comment by teonnik** [comment]
I have the exact same version. I have a dual-monitor setup (laptop and a big monitor) with 4 virtual desktops. Each virtual desktops spans the two monitors (I would prefer it it didn't but couldn't figure out how to force one virtual desktop per screen).

It didn't work for me on virtual desktop number 2, curiously, I just tried on a different virtual desktop and it does work.... perhaps the problem is related to my multi-monitor setup. I've observed other strange behaviour too: the qt-creator window on virtual desktop number 2 will occupy the entire monitor and will not allow for any other windows to be spawned despite the script having been configured for 1 row, 2 columns per monitor.

**Comment by lingtjien** [comment]
> It didn't work for me on virtual desktop number 2
do you mean virtual desktop `2` on screen `1` or virtual desktop `1` on screen `2`

> the qt-creator window on virtual desktop number 2 will occupy the entire monitor and will not allow for any other windows

What do you have in your configuration for `Client min space` the `name` and `space` variables? By default *creator* is in that list with a `space` value of `1` which means that any client with a name that contains that name, such as Qtcreator will always fully occupy a desktop.

**Comment by teonnik** [comment]
> do you mean virtual desktop 2 on screen 1 or virtual desktop 1 on screen 2?

Each virtual desktop occupies both screens (the laptop screen and the external monitor's screen). I was referring to virtual desktop 2 (out of 4), which had qt-creator on it. I have qt-creator on the monitor and I have other apps on my laptop screen. I am unable to open a new window next to qt-creator (on the monitor's screen)

> What do you have in your configuration for Client min space the name and space variables? By default creator is in that list with a space value of 1 which means that any client with a name that contains that name, such as Qtcreator will always fully occupy a desktop.

Thanks for clarifying , the value is 1. I tried changing it to 2, it didn't work. Perhaps I need to restart?

**Comment by lingtjien** [comment]
Yes, all the settings are only loaded in when the script is started. So you can either log out and log in again to restart the window manager or turn the script off and on again

**Comment by lingtjien** [comment]
I assume you figured it out. You can open a new issue if you still have the issue.
