### ISSUE TITLE
Issues on Manjaro

### ISSUE THREAD

**Issue by madjoe** [lingtjien/Grid-Tiling-Kwin#41]
Hi! Looks like a very handy tool for multitaskers. Thanks for your work!

I have an issue whilst following your installation instructions on my Manjaro:
"The desktop entry of type Service is unknown."

I tried to replace the type=Service with type=Application, but it brought me to another issue: 
"The desktop entry file file:///home/me/Grid-Tiling-Kwin/metadata.desktop is not valid."

Any thoughts on that?

**Comment by lingtjien** [comment]
I'm pretty sure the `Type` should be `Service` because if you go to `/usr/share/kwin/scripts/videowall` which contains an example script provided by the KDE developers the value is also `Service` (but to be honest, I just copied this metadata file and changed the names). Also, I believe a have multiple Manjaro users and you're the first one with this problem, so I don't think that's the problem.

Could you try the `Normal Installation` instructions but change the last step from `ln -s` to `cp`?

**Comment by madjoe** [comment]
Nothing has changed after completed a Normal Installation with `cp` at the end instead of `ln -s`.
I checked my journal:
```
04. 07. 2019. 11:37	plasmashell	New URI "file:///home/me/.local/share/kservices5/" "" ""
04. 07. 2019. 11:37	kwin_x11	file:///home/me/.local/share/kwin/scripts/kwin-script-tiling/contents/code/tilelist.js:353: ReferenceError: KWin is not defined
04. 07. 2019. 11:37	plasmashell	New URI "" "" ""
04. 07. 2019. 11:37	dolphin	org.kde.knotifications: Audio notification requested, but sound file from notifyrc file was not found, aborting audio notification
04. 07. 2019. 11:37	kwin_x11	file:///home/me/.local/share/kwin/scripts/kwin-script-tiling/contents/code/tilelist.js:353: ReferenceError: KWin is not defined
```

**Comment by lingtjien** [comment]
I don't think that's my code and I base that observation on the following:

1. kwin-script-tiling is a different kwin tiling script https://github.com/kwin-scripts/kwin-tiling/tree/master/contents/code, mine is called `grid-tiling-kwin` not `kwin-script-tiling`
2. My script only contains the `main.js` file in `contents/code` as you can see in my repository https://github.com/lingtjien/Grid-Tiling-Kwin/tree/master/contents/code, whereas the other project does actually contain a `tilelist.js` file, as you can see here https://github.com/kwin-scripts/kwin-tiling/tree/master/contents/code

**Comment by madjoe** [comment]
Sorry, I had to disable the other script (kwin-script-tiling). This is my journal with your script only:

```
04. 07. 2019. 11:52	plasmashell	New URI "file:///home/me/.local/share/kservices5/" "" ""
04. 07. 2019. 11:52	plasmashell	New URI "" "" ""
04. 07. 2019. 11:52	kwin_x11	qt.qpa.xcb: QXcbConnection: XCB error: 3 (BadWindow), sequence: 28432, resource id: 109052003, major code: 19 (DeleteProperty), minor code: 0
04. 07. 2019. 11:52	kwin_x11	qt.qpa.xcb: QXcbConnection: XCB error: 3 (BadWindow), sequence: 28436, resource id: 109052003, major code: 18 (ChangeProperty), minor code: 0
04. 07. 2019. 11:52	kwin_x11	qt.qpa.xcb: QXcbConnection: XCB error: 3 (BadWindow), sequence: 28443, resource id: 109052003, major code: 19 (DeleteProperty), minor code: 0
04. 07. 2019. 11:52	kwin_x11	qt.qpa.xcb: QXcbConnection: XCB error: 3 (BadWindow), sequence: 28444, resource id: 109052003, major code: 18 (ChangeProperty), minor code: 0
04. 07. 2019. 11:52	kwin_x11	qt.qpa.xcb: QXcbConnection: XCB error: 3 (BadWindow), sequence: 28445, resource id: 109052003, major code: 19 (DeleteProperty), minor code: 0
04. 07. 2019. 11:52	kwin_x11	qt.qpa.xcb: QXcbConnection: XCB error: 3 (BadWindow), sequence: 28446, resource id: 109052003, major code: 19 (DeleteProperty), minor code: 0
04. 07. 2019. 11:52	kwin_x11	qt.qpa.xcb: QXcbConnection: XCB error: 3 (BadWindow), sequence: 28447, resource id: 109052003, major code: 19 (DeleteProperty), minor code: 0
04. 07. 2019. 11:52	kwin_x11	qt.qpa.xcb: QXcbConnection: XCB error: 3 (BadWindow), sequence: 28448, resource id: 109052003, major code: 7 (ReparentWindow), minor code: 0
04. 07. 2019. 11:52	kwin_x11	qt.qpa.xcb: QXcbConnection: XCB error: 3 (BadWindow), sequence: 28449, resource id: 109052003, major code: 6 (ChangeSaveSet), minor code: 0
04. 07. 2019. 11:52	kwin_x11	qt.qpa.xcb: QXcbConnection: XCB error: 3 (BadWindow), sequence: 28450, resource id: 109052003, major code: 2 (ChangeWindowAttributes), minor code: 0
04. 07. 2019. 11:52	kwin_x11	qt.qpa.xcb: QXcbConnection: XCB error: 3 (BadWindow), sequence: 28451, resource id: 109052003, major code: 10 (UnmapWindow), minor code: 0
04. 07. 2019. 11:52	plasmashell	New URI "file:///home/me/.local/share/kservices5/" "" ""
04. 07. 2019. 11:53	kwin_x11	qt.qpa.xcb: QXcbConnection: XCB error: 3 (BadWindow), sequence: 29239, resource id: 109052008, major code: 18 (ChangeProperty), minor code: 0
04. 07. 2019. 11:53	plasmashell	file:///usr/share/plasma/plasmoids/org.kde.plasma.taskmanager/contents/ui/Task.qml:375: TypeError: Type error
04. 07. 2019. 11:53	plasmashell	file:///usr/share/plasma/plasmoids/org.kde.plasma.taskmanager/contents/ui/Task.qml:347: Unable to assign [undefined] to int
04. 07. 2019. 11:53	plasmashell	New URI "" "" ""
04. 07. 2019. 11:53	kwin_x11	qt.qpa.xcb: QXcbConnection: XCB error: 3 (BadWindow), sequence: 29261, resource id: 41943563, major code: 18 (ChangeProperty), minor code: 0
```

**Comment by lingtjien** [comment]
If you followed the instructions you should have a `kwin-script-grid-tiling.desktop` file in `~/.local/share/kservices5/`

so please check that with `ls ~/.local/share/kservices5/` and check that the file actually contains the data `cat ~/.local/share/kservices5/kwin-script-grid-tiling.desktop`

Also, these steps are there to allow you to access the UI to change parameters (because kpackagetool5 is still broken). Only this step `kpackagetool5 --type KWin/Script -i *path*` is needed to install the script, which should the show up in the kwin script dialog. So do you usee grid-tiling in the kwin script dialog module?

**Comment by madjoe** [comment]
```
$ cat ~/.local/share/kservices5/kwin-script-grid-tiling.desktop
[Desktop Entry]
Name=Grid-Tiling
Comment=Automatically tile new windows with gaps in any grid size
Icon=preferences-system-windows-script-test
Type=Service

X-Plasma-API=javascript
X-Plasma-MainScript=code/main.js

X-KDE-PluginInfo-Author=LinG
X-KDE-PluginInfo-Name=grid-tiling
X-KDE-PluginInfo-Version=0.0.1

X-KDE-PluginInfo-Depends=
X-KDE-PluginInfo-License=GPL
X-KDE-ServiceTypes=KWin/Script,KCModule

X-KDE-Library=kwin/effects/configs/kcm_kwin4_genericscripted
X-KDE-PluginKeyword=grid-tiling
X-KDE-ParentComponents=grid-tiling
```

When I double-click `kwin-script-grid-tiling.desktop`, I get the error as stated previously:

> The desktop entry of type Service is unknown.

I can see the grid-tiling in kwin scripts and I enabled it. There's also a button to configure it and it shows up the settings window.

**Comment by lingtjien** [comment]
Errr okay... so you have the script installed and you have access to the UI window and you enabled the script...

So what doesn't work?

Kwin script are plugins for KWin, you can't run them standalone (at least not as far as I'm aware off). So there is not much reason to `run` the .desktop file? What do you expect to happen by double-clicking the .desktop file?

**Comment by madjoe** [comment]
I'm obviously new with kwin. It works now, thanks. 
Is there a setting I could change to set the opacity **of an active window** to noOpacity?
How can I quickly toggle between grid/float mode?

**Comment by lingtjien** [comment]
my script only has 2 modes, all windows with opacity or without and it allows you to specify the amount of opacity. It currently does not support different opacities for different windows.

I don't understand what you mean by floating or grid mode?

This script always tiles all clients but it has a few clients which are always ignored (such as the desktop itself) and it allows the user to expand this list. It also allows the user to float clients manually by global shortcut and it provides a list which the user can use to specify clients they want to float at startup instead of tile.

**Comment by madjoe** [comment]
It could be a great feature to know which windows is currently active by noticing different opacity of the active window.

I mean, how can I quickly enable/disable this grid tiling mode? I guess that would be related to enabling/disabling kwin... `M+S+F11` (Toggle Tiling) doesn't seem to work.

**Comment by lingtjien** [comment]
There are also things you can do with themes, to theme active windows differently and stuff but I'd like to leave that to those themes for now.

If you're asking how to turn the script on and off quickly, I don't know. I've always done it through the KWin script dialog, but I would assume you can do it with a command as well, I just don't know that command. Maybe ask on the KDE subreddit/forums, if someone else can help you with that

**Comment by madjoe** [comment]
I've just found out the key command is this:
`qdbus org.kde.KWin /Scripting script-path`
