### ISSUE TITLE
Suggestion: Moving Focus

### ISSUE THREAD

**Issue by trst** [lingtjien/Grid-Tiling-Kwin#43]
Before I start: love your work. Use it everyday!

Is it possible to surface shortcut commands for moving focus to the next/previous window? Previously, I had mapped move focus in i3, or in tmux/vim to a hotkey plus h,j,k,l (arrow keys work as well but they're not my preferred movement keys) and it would be dynamite if I could do the same in KDE.

I realize that you can Alt+Tab to choose the active window, but the movement keys feel more efficient.

**Comment by lingtjien** [comment]
If you mean changing the currently active window with global shortcuts, I think this section in the README is what you're looking for? (These are provided by default by KWin itself)

> set shortcuts `Switch To Window *Left/Up/Down/Right*` to `Meta+Alt+*Left/Up/Down/Right*`

**Comment by trst** [comment]
Doh! You’re absolutely correct, I’m not sure how I missed that.

Thanks 😅
