### ISSUE TITLE
Plasma freezes on opening system settings

### ISSUE THREAD

**Issue by rain0r** [lingtjien/Grid-Tiling-Kwin#46]
When I got windows open and arranged in a grid and open the system settings application, the UI freezes completley. Moving the mouse is still possible, but not activating any windows. There's no solution but to restart the X server.

This does not happen when no X applications are open.

Versions:
OS: Gentoo Linux
KDE Plasma Version:  5.17.0
KDE Frameworks Version: 5.63.0
Qt Version: 5.12.5

**Comment by lingtjien** [comment]
I'm on the same versions of KDE Plasma and KDE Frameworks as you but I'm on Qt 5.13.1 (Though I am on Arch Linux) so the most straightforward suggestion I have is to try to upgrade your Qt version.

If that doesn't work you'll have to elaborate on this part a bit more and provide how you get to this state from a fresh reboot.

Based on your description I'm assuming the steps you've taken are:
1. Fresh reboot
2. open Konsole
3. open system settings
4. opening a new instance of Konsole

Where the 4th step fails for you, but I just tried it with a fresh reboot and it works fine for me...

**Comment by rain0r** [comment]
My steps to reproduce are:

1. Fresh reboot
2. Login
3. 4 applications start due to autostart
4. Open system settings via start menu
5. System freezes

Updating QT is a bit "difficult" because there's no newer version in portage.

**Comment by lingtjien** [comment]
if you leave out step 3 (disable the autostarts) does it happen then as well?

what are these 4 applications you're autostarting? Does it also happen if you start 4 instances of Konsole for example?

**Comment by rain0r** [comment]
No, it doesn't happen when autostart is disabled.
The four Applications are:

 * Firefox
 * Thunderbird
 * rxvt-unicode
 * Signal-Desktop

It also doesn't happen with 4 instances of Konsole.

**Comment by lingtjien** [comment]
Does it also happen without this script enabled?

can you single out which one(s) of these 4 is causing it?

**Comment by lingtjien** [comment]
I'm assuming it's related to #47, if not then you can open a new ticket with a minimal working example
