### ISSUE TITLE
Full Screen when only one app is running in desktop

### ISSUE THREAD

**Issue by hugues31** [lingtjien/Grid-Tiling-Kwin#49]
Hello !

First, thank you very much for your script. I use it on a daily basis :)
Now, I would want to make an app "fullscreen" (no margin) when there is only one application on my virtual desktop. How could I achieve that ?

Thanks in advance

**Comment by andrei-pavel** [comment]
I like this change.

One disadvantage though: panel / dockbar would be hidden

**Comment by lingtjien** [comment]
KWin already provides a global shortcut for that, called `Make Window Fullscreen`

**Comment by hugues31** [comment]
I do not want the app make the dockbar/panel disappear. Only that margins get removed

**Comment by andrei-pavel** [comment]
> I do not want the app make the dockbar/panel disappear. Only that margins get removed

That's an important distinction. Fullscreen draws the window over the panel.

> KWin already provides a global shortcut for that, called `Make Window Fullscreen`

I think what @hugues31 wants is for this to be done automatically whenever one window remains on a screen.

**Comment by hugues31** [comment]
I just want Grid Tiling to automatically remove the margin when there is only one window remaining on a virtual desktop :) How feasible is this ?

**Comment by lingtjien** [comment]
Probably not very feasible, it would probably result in a lot of conditional code for something that's quite a niche feature (in my opinion). However implementing a `make fullscreen` global shortcut that takes into account the panels that you have would be quite easy to achieve and independent of the rest
