### ISSUE TITLE
Moving windows with default kwin shortcuts

### ISSUE THREAD

**Issue by TheIdealis** [lingtjien/Grid-Tiling-Kwin#5]
If I use the kwin-actions `Window One Desktop to the <direction>` or `Window to Desktop <number>`, the moved window will keep its shape and jump back to its original desktop, if I create a new window. 
Unfortunately, there is no Tiling-Gaps-action to move windows up and down, to only to move them to the next or previous desktop. Is it possible, to use the default kwin-actions together with your tiling-script?

**Comment by lingtjien** [comment]
No... unfortunately not, because the data is stored in my script separately... It wouldn't be very difficult to add though. So I'll mark it as a feature request. I was planning to revamp a lot once I find some spare time anyway...

**Comment by lingtjien** [comment]
Small little heads up, I'm almost done with the refactoring and I already implemented this feature. Just a few more things to fix and I'll push it to GitHub (hopefully this weekend, else next)

**Comment by lingtjien** [comment]
Added the feature in the new branch, it's not quite finished yet but you can give it a try.
