### ISSUE TITLE
respect Activities / isolate windows to one Activity

### ISSUE THREAD

**Issue by jayarmstrong** [lingtjien/Grid-Tiling-Kwin#52]
Hi,
By default, I'm seeing this script place every window into every Activity I have. This breaks the usefulness of Activities.

**Comment by lingtjien** [comment]
the script does or at least should not change the activity of the clients. Actually, I wanted to implement some shortcuts for moving clients between activities but the API of KWin does not alloy changing this parameter as it is *read only* as far as I know.

So the script doesn't change the activity of the client and even if I wanted too, KWin doesn't allow it. An old version of this script didn't support activities so it would then ignore activities all together.

I personally don't use activities but I assume clients remember their activity so once you change it to the desired one you'll be good to go? The only way I know to change activities is

1. `enable borders`
2. `click icon`
3. `show in activities`
4. choose one of the desired option

**Comment by lingtjien** [comment]
I assume you found the activity switcher

**Comment by jayarmstrong** [comment]
Hi, and thanks for the explanation. 

The issue seems to have nothing to do with your script but simply showed up the same day I installed and tested the script. I believe I can override the behavior using the "configure special application settings" option.
