### ISSUE TITLE
Shortcuts that don't work

### ISSUE THREAD

**Issue by j0hannes** [lingtjien/Grid-Tiling-Kwin#55]
I have two machines with identical setup (I hope). On one of them, tiling works, the shortcuts do their job and everything's fine. On the other machine, most shortcuts do work, but some of them don't, like increasing or decreasing the size (but the window is flickering when I press them). What could be the reason for that? What does the script need to do its job?

**Comment by lingtjien** [comment]
Try resetting the settings back to default (the set to default button is in the bottom left of the UI normally). `dividerBounds` controls how much you can increase and decrease the size of a client. What settings are you using?

**Comment by j0hannes** [comment]
Yes, know it works. No idea what was wrong.
