### ISSUE TITLE
Is there a list of kewyboard shortcuts?

### ISSUE THREAD

**Issue by David-Frick** [lingtjien/Grid-Tiling-Kwin#56]
Sorry, I am very new to tiling managers. I was wondering if there is a list of keyboard shortcuts and how to tweak settings anywhere? Really hoping to vamp up my workflow timing with this!

Thanks for this cool project!

David

**Comment by lingtjien** [comment]
if you open the kwin section in global shortcuts (type `shortcut` in krunner for example) and search for `Grid-Tiling` you should find all the shortcuts that I provide, on top of that I tried to support as many default ones as well. The one that I provide you can find in the README with a short explanation

**Comment by David-Frick** [comment]
Sweet. Much appreciated!

-------- Original Message --------
