### ISSUE TITLE
Turn off and then on grid-tiling makes every windows are full screen?

### ISSUE THREAD

**Issue by xversion1** [lingtjien/Grid-Tiling-Kwin#57]
So if I'm using grid-tiling and turn it off, and then turn it on again, I thought the windows will automatically tile but they're all in full screen instead. I have to Alt-tab around to focus on all windows all over again to make them tile.

**Comment by lingtjien** [comment]
Yeah the script doesn't do a refresh automatically on startup currently. So you'll have to press the global shortcut `Grid-Tiling: Refresh` once and it will loop through all the clients. Maybe I should add that to the startup.

**Comment by xversion1** [comment]
Press the refresh shortcut causes another problem. It brings others clients from other work-spaces to the current workspace. It's weird that it didn't bring all clients, some left out I don't know why.

**Comment by lingtjien** [comment]
And by workspaces you mean, virtual desktops? If so then yes, it loops through all clients and tries to tile them, which is going to make them tile to your current virtual desktop until it's full and then the next, and so forth.

Define "some clients" and also your settings (you can specify clients to be always ignored by the script in the settings)

**Comment by lingtjien** [comment]
you can give the dev branch a try, it should now attempt to tile all clients on startup and unlike previously, it should tile them to the desktop and screen that they are started on instead of the active one.

**Comment by lingtjien** [comment]
assuming it's fixed, otherwise you can open a new ticket
