### ISSUE TITLE
Ignored clients list is ignored

### ISSUE THREAD

**Issue by Begggs** [lingtjien/Grid-Tiling-Kwin#58]
Arch linux, newest KDE apps, tried to write some apps to ignored clients list in ~/.local/share/kwin/scripts/grid-tiling/contents/config/main.xml but nothing changed, even after few reboots and script enabling/disabling

**Comment by Begggs** [comment]
Ok i found that i can edit this list right in the code of script

**Comment by lingtjien** [comment]
normally you would change these values in the UI from this script in KWin and then reboot to apply them.
