### ISSUE TITLE
Move (Next/Previous) Desktop/Screen shortcut issues with multiple displays

### ISSUE THREAD

**Issue by felixwoolford** [lingtjien/Grid-Tiling-Kwin#59]
Firstly, thank you for your work on this. I have had a wonderful time using it with a single display for the past 6 months or so.

Now I am having issues with the Move Next/Previous Desktop/Screen shortcuts with multiple displays, somewhat different to those in #28. 
Firstly, neither shortcut works to move to the other screen, although this is not a problem as the standard kwin shortcut for that seems to be working okay.
Secondly, each shortcut only works for one screen, i.e Move Previous Desktop/Screen only works to shift to the previous desktop on my primary display, and Move Next Desktop/Screen only works to shift to the next desktop on my secondary display.
This means that to for shift a window to the next desktop on my main display requires a tedious string of shortcuts switching between screens and potentially messing up tiling.

This happens with any number of rows and columns.

**Comment by lingtjien** [comment]
currently in the progress of refactoring/updating a lot of the code related to multi-screen, so hopefully that solves this for you. Otherwise, I'll have to dive a bit deeper, but I'm also going to change some of the logic related to these specific shortcuts most likely.

**Comment by lingtjien** [comment]
Hmm, I've been working on it but it seems that the API of KWin has changed, the `screen` property that I use to change the screen on which a client resides seems to now be `readonly` so it seems like the API does not allow any developer to change the screen on which a client resides... weird.

Also other things have changed in the API, the `desktop` variable now states that it should not be used directly but to use `isOnDesktop()` instead but it does not list this method in the documentation...

**Comment by felixwoolford** [comment]
Ok thanks for this. At the moment I am using the kwin shortcuts to send windows to numbered desktops, this is a reasonable workaround.

**Comment by lingtjien** [comment]
It has been added to the KWin API since version 5.18. I added the necessary changes to the script for these changes and gave it a quick test. So if you're running KWin 5.18 feel free to give it a try, multi screen support should work normally again

**Comment by lingtjien** [comment]
assuming it's fixed, otherwise you can open a new ticket
