### ISSUE TITLE
Move windows in diferents screens

### ISSUE THREAD

**Issue by jerlockk** [lingtjien/Grid-Tiling-Kwin#6]
The movement and change of windows between different screens is blocked

**Comment by lingtjien** [comment]
You'll have to be a bit more specific on what the problem is... I tried moving clients from within a different screen into another screen using the supplied shortcuts and it worked fine.

**Comment by jerlockk** [comment]
I can not move windows to another screen, neither with the shortcuts nor with the mouse unless on a screen I open 4 applications which is the limit

**Comment by lingtjien** [comment]
I suppose that answers your question. You can submit a new ticket if you still need more clarification
