### ISSUE TITLE
Option to disable gaps if only one window?

### ISSUE THREAD

**Issue by lanrat** [lingtjien/Grid-Tiling-Kwin#60]
Is it possible to disable gaps on a virtual desktop if there is only one window to display?

**Comment by lingtjien** [comment]
currently not, doing it automatically when only one client is present on the virtual desktop is a bit more difficult. However, adding a global shortcut to increase/decrease/disable/enable the gaps should be straight forward, if that suits your needs?

**Comment by lingtjien** [comment]
You can try the dev branch added a global shotcut `Grid-Tiling: Toggle Gap` (Default `Meta+G`)

**Comment by lingtjien** [comment]
assuming it's fixed, otherwise you can open a new ticket
