### ISSUE TITLE
Kwin < 5.18

### ISSUE THREAD

**Issue by JStyle21** [lingtjien/Grid-Tiling-Kwin#70]
Hi,

I just spend around an hour trying to get this to work after it suddenly stopped working, I assume this happened due to a recent git pull that got the master branch version which apparently now depends on kwin >=5.18...
Honestly if i didn't find a comment on reddit mentioning this, i probably wouldn't have figured it out so fast.

It's good that the <5.18 branch exists, but it should at least be mentioned in the README

**Comment by lingtjien** [comment]
Added to the readme, thank you
