### ISSUE TITLE
Edit margins

### ISSUE THREAD

**Issue by KBeDevel** [lingtjien/Grid-Tiling-Kwin#72]
Is there any way to modify the tiles margins in pixels?

I have tried modifying the fields top, left, right and bottom from the "Margins" section in the script configuration window, but there are no visible changes.

Thank you in advance, this script is very useful to me.

**Comment by KBeDevel** [comment]
I realized the changes can only be viewed after a session re-login and/or a script restart

**Comment by lingtjien** [comment]
Glad you figured it out :)

The settings are only loaded at startup so you have to either `reboot`, `logout -> login` or you can `script off, apply it, turn it back on and apply it again` as per the third point in the `Useful to know` section in the readme
