### ISSUE TITLE
Multiple monitors don't work

### ISSUE THREAD

**Issue by dj-d** [lingtjien/Grid-Tiling-Kwin#73]
Hi, unfortunately I was unable to make the application work with multiple monitors. That is, when I only use the laptop monitor there are no problems and everything works correctly, but when I use more than one monitor nothing works. There is a solution?

**Comment by lingtjien** [comment]
You'll have to elaborate a bit more on what exactly doesn't work.

1. which version of the script (branch) are you running and which KWin version?
2. restore the settings to default, connect the second monitor and reboot. Then try to open multiple terminals (konsole for example) on the first virtual desktop on your first screen (so this will be your laptop screen). What happens?

**Comment by dj-d** [comment]
I used the branch master with the latest KWin version. Using just one monitor everything works correctly. Using more than one monitor the script does not work, that is, windows are managed with the standard kde window manager. It is as if the script doesn't really work

**Comment by lingtjien** [comment]
Latest KWin version depends on your distro but I assume 5.18 or above, which should be fine for master.

Could you please execute step 2 and tell me what you observe in every part of the step, so I can compare your behavior with the one that I observe

**Comment by dj-d** [comment]
I use Manjaro-KDE 20.0.1. Now i try

**Comment by dj-d** [comment]
What do you mean by step 2?

**Comment by lingtjien** [comment]
> 2\. restore the settings to default, connect the second monitor and reboot. Then try to open multiple (at least 5, with a few seconds between them) terminals (konsole for example) on the first virtual desktop on your first screen (so this will be your laptop screen). What happens?

**Comment by dj-d** [comment]
Nothing, they are simply opened one above the other

**Comment by dj-d** [comment]
I did other tests and maybe I came to the conclusion that the problem is my thunderbolt 3 dock. Because I tried to turn on the laptop without connecting any monitor, then connect it later and everything worked. The second test was to turn on the laptop with the monitor already connected (via HDMI) and, restarting the scratch, everything seems to be working correctly. The only doubt is that I don't know if the problem is only for my dock or all thunderbolt 3 docks.

**Comment by dj-d** [comment]
I have done other tests and the result is that the script works with a maximum of 2 monitors. I tried to attach several monitors to the laptop both directly and through the thunderbot 3 dock and in all cases, it turned out that when the total number of monitors exceeds 2, the script no longer works. So, I can confirm that the script works with up to 2 monitors.

**Comment by lingtjien** [comment]
Aha okay then it makes sense. I also put a section in the ReadMe regarding this (and made it bold)

> you **must** supply a grid for every screens that you have connected (and plan to connect)

By default only 2 grids are supplied, `row` `2,2` and `column` `2,3`. So you need to supply another grid size that you want to use for your 3rd monitor (if you plan to connect a 4th monitor at any time you should supply a grid for that one too)

For example `row` `2,2,3` and `column` `2,3,3`, whill result in a 2x2 grid on your first screen, a 2x3 grid on your second screen and a 3x3 grid on your 3rd screen

**Comment by dj-d** [comment]
Perfect, I test and communicate the result

**Comment by lingtjien** [comment]
Made the default grid size list longer (up to 10 screens). So hopefully this was your issue

**Comment by dj-d** [comment]
I tried and now it works, although the first time I tried to do it it was not gone, but the important thing is that now it works

**Comment by lingtjien** [comment]
Probably because the script requires a restart when you change any of the settings, anyways merged it to master
