### ISSUE TITLE
Automatic tiling mode on session startup

### ISSUE THREAD

**Issue by Occhioverde** [lingtjien/Grid-Tiling-Kwin#74]
I installed the script a few days ago and I immediately realized a rather annoying problem.
In fact, when I start the Plasma session, the windows are opened in floating and non-tiling mode as I should expect.
To re-enable the function, I therefore need to go to Settings > Kwin Scripts and disable/re-enable the script.
Is there a system to start the tiling mode directly when the session opens?

**Comment by lingtjien** [comment]
What are the settings you are using? (screenshot please)

There is a checkbox in the settings called `Tile`, this one determines if the script starts in tiling or floating mode. But your case sounds like the script died at startup, which would be different...

**Comment by Occhioverde** [comment]
![Tiling Settings](https://user-images.githubusercontent.com/18429412/82152815-2bf74b80-9864-11ea-9d6f-06eb8440a8e3.png)

These are my settings. As you can see all the items are set as default and the script is active.

**Comment by lingtjien** [comment]
Hmm, some logging information would be nice. It sounds like the script dies at startup, so I'd be interested in the error it spits out when it does.

You may be able to find the logging in your system logging but if not, this is how I do it.

1. open a terminal and type `kdebugsettings` this will open a UI that allows you to toggle logging for different KDE applications, the section I'm interested in is called `KWin Scripting`, so turn that one to `Full Debug` (`Critical` by default), click `apply` then `ok` and close the window
2. now we restart KWin from the terminal and replace the current running instance, so we can see the logging in the terminal `kwin_x11 --replace &`
3. please post the logging (you will see a lot of XCB errors, but apparantly those are normal and caused by QT, so just ignore those)

**Comment by Occhioverde** [comment]
Excluding all "BadWindow" errors, this is the only error that comes from KWin.
I hope it can help.
```
21/05/20 16:55	kwin_x11	kwin_scripting: defaultscript encountered an error at [Line  578 ]
21/05/20 16:55	kwin_x11	kwin_scripting: Message:  "TypeError: Result of expression 'this.desktops[i]' [undefined] is not an object."
21/05/20 16:55	kwin_x11	kwin_scripting: -----------------
21/05/20 16:55	kwin_x11	kwin_scripting:   "message" :  "Result of expression 'this.desktops[i]' [undefined] is not an object."
21/05/20 16:55	kwin_x11	kwin_scripting:   "lineNumber" :  "578"
21/05/20 16:55	kwin_x11	kwin_scripting:   "sourceId" :  "139961711630400"
21/05/20 16:55	kwin_x11	kwin_scripting:   "fileName" :  ""
21/05/20 16:55	kwin_x11	kwin_scripting:   "expressionBeginOffset" :  "17448"
21/05/20 16:55	kwin_x11	kwin_scripting:   "expressionCaretOffset" :  "17464"
21/05/20 16:55	kwin_x11	kwin_scripting:   "expressionEndOffset" :  "17474"
```

**Comment by lingtjien** [comment]
Interesting, looks like the client that the script is trying to tile has an invalid desktop number. I suspect it's on all desktops and has thus an index of -1. Let's check if that's the case.

Would you be so kind to add the following below line 570 (`var i = client.desktop - 1`)
`print(client.resourceName.toString() + ' ' + client.desktop + ' ' + i);`

Try it again and post the output

**Comment by Occhioverde** [comment]
I think I managed to solve the problem unintentionally.
While applying the change you suggested, I opened Yakuake and, noting that it was not ignored by default, I inserted it among the clients not to be placed in tiled mode.
Then restarting KWin the script started just as it should, without showing the error that I had reported before and in fact, reverting the change, the KWin log reports this:
```
21/05/20 19:27	kwin_x11	kwin_scripting: "/home/rsacchetto/.local/share/kwin/scripts/grid-tiling/contents/code/main.js" : "yakuake -1 -2"
21/05/20 19:27	kwin_x11	kwin_scripting: defaultscript encountered an error at [Line  579 ]
21/05/20 19:27	kwin_x11	kwin_scripting: Message:  "TypeError: Result of expression 'this.desktops[i]' [undefined] is not an object."
21/05/20 19:27	kwin_x11	kwin_scripting: -----------------
21/05/20 19:27	kwin_x11	kwin_scripting:   "message" :  "Result of expression 'this.desktops[i]' [undefined] is not an object."
21/05/20 19:27	kwin_x11	kwin_scripting:   "lineNumber" :  "579"
21/05/20 19:27	kwin_x11	kwin_scripting:   "sourceId" :  "140592401999936"
21/05/20 19:27	kwin_x11	kwin_scripting:   "fileName" :  ""
21/05/20 19:27	kwin_x11	kwin_scripting:   "expressionBeginOffset" :  "17524"
21/05/20 19:27	kwin_x11	kwin_scripting:   "expressionCaretOffset" :  "17540"
21/05/20 19:27	kwin_x11	kwin_scripting:   "expressionEndOffset" :  "17550"
```

**Comment by lingtjien** [comment]
Great, so that confirms my hypothesis. I need to build an extra check in the validator to filter out these clients which have a desktop number of `-1`

**Comment by Occhioverde** [comment]
No problem.
Let me know when you implement this change, so I can test the script without ignoring Yakuake.

**Comment by lingtjien** [comment]
You want Yakuake to be tiled? I assumed that since it's visible on all virtual desktops, that you would want it, to **not** be **tiled**, since tiling means that it has to be tiled to a specific virtual desktop?

**Comment by Occhioverde** [comment]
No, of course, I meant that I was going to try with Yakuake to verify that the problem didn't show up in similar situations anymore.

**Comment by lingtjien** [comment]
Added an extra check, so now the script shouldn't crash. I installed yakuake and tried it shortly but it seems that application sometimes has a desktop number of `-1` and sometimes it's a valid number. So it's best to ignore that application regardless, else it'll be tiled sometimes.

**Comment by Occhioverde** [comment]
Perfect, I did a test by starting the session without excluding Yakuake and it seems that no more crash phenomena will occur. Obviously, as we already said, it is better to avoid placing Yakuake on the grid, but at least it seems that the problem is solved.
I would say that the issue can be considered closed; thank you very much for helping.
