### ISSUE TITLE
reactivate border for window when transitioning from tile to float.

### ISSUE THREAD

**Issue by RomuloPBenedetti** [lingtjien/Grid-Tiling-Kwin#75]
When I make a window tiled and tile windows are without border, the window lose border as expected, but when I make it float again, it will not regain border.

**Comment by lingtjien** [comment]
Give the dev branch a try

I made it restore the initial border and geometry on float, but I'm not sure if this is the best solution. Thinking about centering the client in the middle of the virtual desktop at a certain size (defined by user) and with or without border (also defined by user)

**Comment by RomuloPBenedetti** [comment]
I think the idea of you being able to centering it or not when going to float mode, with a user specified  size, is really good. I'm also fine with a `floating client properties` to specify whether they have borders or not as I can get the same result, **always border when floating**.

Will try the branch, thanks!

**Comment by lingtjien** [comment]
I assume you haven't had problems with it, so merged back to master. I just went with the restore initial geometry for now, since it requires less code and less configuration. Maybe I'll change it in the future, if people want it :)
