### ISSUE TITLE
Grid-Tiling: Maximize shortcut not available

### ISSUE THREAD

**Issue by Richard-Payne** [lingtjien/Grid-Tiling-Kwin#76]
I don't see Grid-Tiling: Maximize in the shortcut list.  Is it the software or the documentation that is wrong?

**Comment by lingtjien** [comment]
KWin already provides a maximize shortcut by default called `Maximize Window`.

This script provides a toggle that minimizes all other clients (or unminimized all others, if there is only 1 or none unminimized open), which functions kind of a like a maximize, but taking gaps into account

What behavior are you looking for?

**Comment by Richard-Payne** [comment]
I'm not particularly.  There was a discrepancy between the documentation and the shortcuts provided by the scripts.  From the sound of what you said, you just need to fix the documentation.

**Comment by lingtjien** [comment]
Which shortcut provided by the script is not in the documentation? (I believe I used to have a maximize shortcut long ago, but you have to manually remove unused shortcuts, it doesn't happen automatically)

**Comment by Richard-Payne** [comment]
Other way around.  The documentation mentions "Grid-Tiling: Maximize" but no such action is available in the Global Shortcuts list under kwin.  There's actually another couple that are the same, "Grid-Tiling: Float" and "Grid-Tiling: Tile".

**Comment by lingtjien** [comment]
I think you're looking at old documentation. Those tile and float shortcuts have been combined some time ago. I assume you're looking at the readme.md directly in your checkout, so which commit are you on?

**Comment by Richard-Payne** [comment]
Ah, you're right.  Somehow I ended up here: https://freesoft.dev/program/110171488
The github master doesn't have those shortcuts, as you said.
