### ISSUE TITLE
Anyone interested in a 'Spiral Tiling' feature?

### ISSUE THREAD

**Issue by auwsom** [lingtjien/Grid-Tiling-Kwin#77]
https://github.com/kwin-scripts/kwin-tiling/issues/214

**Comment by lingtjien** [comment]
Thank you for the suggestion (actually interesting reading that post that was linked, where they discuss a certain KWin core design, that I've disagreed with), but if you wanted to do something like this properly, you'd have to start from scratch or a different base in my opinion.

The whole design of the data in this script is made for clients to not be stacked on top of each other, which is the opposite of what you want to achieve

**Comment by auwsom** [comment]
Thanks for your reply @lingtjien. Glad you found that link useful. 

I agree, that it is a different twist, but correct me if I'm wrong, it is the closest functionality to what I want to achieve. I tried to show that by asking about having a 'negative gap' that might only require one setting change to allow overlapping.

Thanks anyway

**Comment by lingtjien** [comment]
I don't do any user input sanity checks and only recently added limits to the values in the UI but inside the script there is no checking internally as far as I'm aware. My fluid mechanics prof used to say *"sht in, is sht out"* when it comes to putting values into programs.

Anyways, a negative gap will result in windows falling outside the screen, for example the `x` position of the first client is calculated as `margin.left + gap` (simplified) so if your gap is negative (and larger than `margin.left`) then the calculated `x` position will be off the screen, unless you correct it using the margins.

I did take a quick test and if you set the gap to `-100` for example and then correct it using the `margin.top` and `margin.bottom` to `100` then the clients will overlap by `100`. You can change this at lines `64`, `75` and `77` in the `main.js`.

You're free to use whatever you like, if you believe that this is a good starting point then, good luck. I simply don't have the time to build such a feature and maintain it, a feature that I would ultimately not use myself, sorry.
