### ISSUE TITLE
usage clarification

### ISSUE THREAD

**Issue by RafalSkolasinski** [lingtjien/Grid-Tiling-Kwin#79]
Nice scripts - really impressive looking from the gifs ; - )

But unfortunately for someone who didn't use KDE script extensions before configuration instructions could be a bit clearer. 
For example information that after installation one need to go to `kwin scripts` to enable script or where to adjust the actual config options would be very useful.

**Comment by lingtjien** [comment]
I always assumed that it went something like this

user becomes aware of kwin scripts -> looks around for usefull kwin scripts for their workflow -> finds my script

So then I assumed that people would already know how to configure and activate kwin scripts, but I guess that assumption is not always right. For those people adding a small section to the readme wouldn't hurt I guess

**Comment by RafalSkolasinski** [comment]
Exactly! Sometimes people find out about kwin scripts when they just look for a given functionality in KDE.

**Comment by lingtjien** [comment]
Added
