### ISSUE TITLE
Installation Guide

### ISSUE THREAD

**Issue by ChadK-II** [lingtjien/Grid-Tiling-Kwin#80]
Hiya
 Still a Linux newbie.
Any pointer why I'm getting this error while trying to install your code.
![image](https://user-images.githubusercontent.com/50655826/89767655-7ed45c80-db4e-11ea-9940-386fece9a650.png)
Running fresh manjaro kde.

**Comment by lingtjien** [comment]
You need the local path to where you cloned this repo to

1. Clone the repository with git, to somewhere locally, you're currently in `~` which means home, in Linux
2. Then run the installation command with the name of the directory that you just cloned with git `Grid-Tiling-KWin`

**Comment by ChadK-II** [comment]
Hi thanks all sorted :+1:
