### ISSUE TITLE
Does the script hide window decorations automatically? 

### ISSUE THREAD

**Issue by zerj23** [lingtjien/Grid-Tiling-Kwin#81]
I thought that it leaves the decorations, but it actually doesn't so i cannot use grab handles. Do you confirm it?

**Comment by CaydendW** [comment]
There is an option in the KWin script manager of this extension. Once the gear icon is clicked it says:  "Border" with a tick before it. Tick that box and reload the script and you will have window decorations.

**Comment by zerj23** [comment]
That's why! Strangely I don't have the gear, I should try to rebuild the script

**Comment by lingtjien** [comment]
Did you do the last 3 steps in the installation instructions? You need a copy of the `.desktop` file in `kservices5` but renamed as `kwin-script-grid-tiling.desktop`

**Comment by zerj23** [comment]
Resync + manual installation solved the issue, thanks!
