### ISSUE TITLE
Cannot use keyboard shortcut to move windows arbitrary desktops

### ISSUE THREAD

**Issue by SirNapkin1334** [lingtjien/Grid-Tiling-Kwin#82]
My issue is very simple: moving an arbitrary window to Desktop _n_ does not work. Nothing happens when I press the keybind. I have tried rebinding it to other things to no avail. It simply doesn't work. Moving windows between relative desktops works (i.e. `META + HOME/END` in the recommended / default configuration), but not moving to an arbitrary desktop. Note I am using only 1 screen.

**Comment by lingtjien** [comment]
Interesting, just gave it a try and it works for me with the default KWin shortcut `Window to Desktop 5` bound to `Meta+Alt+5` and also with the menu from the border with the `Move to Desktop` dropdown.

Which shortcuts are you trying? What happens if you take a clean environment, so after a reboot then start 1 terminal and try to move that to virtual desktop 5 for example?

**Comment by SirNapkin1334** [comment]
I am using `META + SHIFT + <num>` (curiously, in plasma, it displays this as the uppercase form of the number, i.e. `META + SHIFT + !`). After rebooting; nothing, still doesn't work. Not even using `ALT` in place of `SHIFT`. The relative ones still work though.

**Comment by lingtjien** [comment]
And you bound this to the `Window to Desktop #` shortcut?
Have you tried the window menu, that has the `Move to Desktop` option, that allows moving the window to a specific desktop (that should do the same thing, so curious if that works)? 
Which version of KWin are you running (and distro)?

**Comment by SirNapkin1334** [comment]
> And you bound this to the `Window to Desktop #` shortcut?  
Yes.
> Have you tried the window menu, that has the `Move to Desktop` option, that allows moving the window to a specific desktop (that should do the same thing, so curious if that works)?  
What is this window menu you speak of and where can I access it? If you mean the one accessed by right-clicking on the bar of a window, then yes, that works.
> Which version of KWin are you running (and distro)?
kwin 5.19.4; Arch Linux kernal 5.8.5-arch1-1

**Comment by lingtjien** [comment]
> What is this window menu you speak of and where can I access it? If you mean the one accessed by right-clicking on the bar of a window, then yes, that works.

Yeah that's the one, it has options to move the client to any specific desktop.

So latest Arch packages, same as me, hmm

Have you confirmed that none of the `Move to Desktop` shortcuts work (I only tried `Move to Desktop 5`)?

**Comment by SirNapkin1334** [comment]
Yes, none work.

**Comment by lingtjien** [comment]
If you use the `Grid-Tiling: Refresh` shortcut after having done the `Move to Desktop` shortcut, nothing changes either?

Normally, the client is moved to a specific desktop and then the active desktop is changed to that desktop, by "nothing happens" you mean that neither of these two actions happen, right?

(You're using the master branch right?)

**Comment by SirNapkin1334** [comment]
> If you use the `Grid-Tiling: Refresh` shortcut after having done the `Move to Desktop` shortcut, nothing changes either? 

Yes, nothing happens.
> Normally, the client is moved to a specific desktop and then the active desktop is changed to that desktop, by "nothing happens" you mean that neither of these two actions happen, right? 

Yes, I mean that neither happen.
> (You're using the master branch right?) 

Yes.

**Comment by lingtjien** [comment]
Could you please try the following:

- turn on KWin debug logging
1. open a terminal and type `kdebugsettings`
2. search for `kwin`
3. set `KWin Scripting` to `Full Debug`
4. `Apply` and `Ok`
- add logging to source code
1. open `main.js` (in the `contents/code` directory)
2. *before* line 850 (`if (c.desktop === c.desktopIndex + 1 || !tiledClients.hasOwnProperty(c.windowId))`)
3. add `print(c.desktop, c.desktopIndex);`
- restart KWin with output in terminal
1. Open a terminal
2. `kwin_x11 --replace &`
- Try again and post the logging
1. try with the window decoration menu
2. try with the global shortcut

(side note, are you using any other KWin scripts? And which application are you trying to move?)

**Comment by SirNapkin1334** [comment]
>     * restart KWin with output in terminal
> 
> 
>     1. Open a terminal
> 
>     2. `kwin_x11 --replace &`
> 
> 
>     * Try again and post the logging
> 
> 
>     1. try with the window decoration menu
> 
>     2. try with the global shortcut 

Global shortcut (`META + SHIFT + <NUM>`): no output.  
Relative shortcut: (Moving FF from 1 to 2 and back again)  
```
kwin_scripting: "/usr/share/kwin/scripts/grid-tiling/contents/code/main.js" : "firefoxdeveloperedition 2 0"
kwin_scripting: "/usr/share/kwin/scripts/grid-tiling/contents/code/main.js" : "firefoxdeveloperedition 1 1"
```
Window Decoration menu (moving from Desktop 1 to Desktop 3:
```
kwin_scripting: "/usr/share/kwin/scripts/grid-tiling/contents/code/main.js" : "firefoxdeveloperedition 3 0"
```

> (side note, are you using any other KWin scripts? And which application are you trying to move?) 

Scripts: there are 3 other ones, but I think they are installed by default as they are disabled and I don't remember installing them.  
<img width="1502" alt="image" src="https://user-images.githubusercontent.com/31591796/91792252-f3d50800-ebc9-11ea-802e-82988999f362.png"> 

Firefox, Discord Development, konsole, IntelliJ, system settings, probably more. Doesn't work on any applications.

**Comment by lingtjien** [comment]
Interesting, they should all enter this signal when the desktop of a client changes. What happens if you turn of all the KWin scripts, reboot and then try the global shortcut, does it move to the desired desktop?

**Comment by lingtjien** [comment]
I assume you've figured it out by now, otherwise you can open a new ticket
