### ISSUE TITLE
Conditional jumping of windows out of grid

### ISSUE THREAD

**Issue by madjoe** [lingtjien/Grid-Tiling-Kwin#84]
I've just noticed a weird bug and I'm not sure which code causes it, so I will report it here and on the other GitHub project that I use (`feh`):

https://github.com/derf/feh/issues/543#issuecomment-695329855

`Feh` is a very simple and fast image viewer. Whenever I press "Next" (whilst listing JPG images in a slideshow) for upcoming image that is large enough (e.g. 10MB+), the `feh` window suddenly jumps out of grid, so it's not tiled anymore. That's why I always need to press "f" (toggle full screen instruction for `feh`) to get it back to become tiled again. You may try to install `feh` to try to reproduce this issue.

**Comment by lingtjien** [comment]
Does `Grid-Tiling: Refresh` also work to get it back into the grid?

**Comment by madjoe** [comment]
Yes, it does. Just tested it with <kbd>Meta</kbd> + <kbd>R</kbd>.

**Comment by lingtjien** [comment]
Then I'm pretty sure it's the application itself that sets it's geometry to a certain one when you press `next` on an image larger than 10MB
