### ISSUE TITLE
being able to configure defaults

### ISSUE THREAD

**Issue by andaag** [lingtjien/Grid-Tiling-Kwin#85]
Hi

I see there's a config.xml file, but I can't find any ui to configure the defaults. Is it available anywhere?

I'd love to turn on borders by default, it eats a bit of space, but I think it looks nicer 😀

**Comment by lingtjien** [comment]
The configuration UI can be accessed through the same place where you activate the script. There should be a button to the far right of the checkmark This setting button should open the UI window (if you don't see this button then you probably missed the latter of the 3 commands that you need to run for the normal installation instructions)

**Comment by andaag** [comment]
You are absolutely right, copy&paste malfunction 👍. Thank you!
