### ISSUE TITLE
missing window refresh after "move window to desktop"

### ISSUE THREAD

**Issue by andaag** [lingtjien/Grid-Tiling-Kwin#86]
Hi

When having 2 desktops, and using a hotkey to move a window from desktop1 to desktop2 the window lands on top and floating, instead of falling into the grid.

Trying to move the window instantly "grid's" it.

Any way to trigger a recalculation of the grid positions after a window has been moved?

(I'm testing moving to this i3, kudos! I've always wanted "as close to i3 as I can get" experience, but still taking advantage of some of kwin's nice features. This is the only one I've found that's close to perfect, and I have been trying for a while + some quick attempts on writing my own a while back 😀)

**Comment by lingtjien** [comment]
Which application are you trying to move? And does it correctly tile a geometry respecting application, like konsole?

**Comment by andaag** [comment]
I just tried with 3 konsole windows.

2 open on virtual desktop 2, one open on desktop 3. Moving from 3 to 2 means the 2 previous ones stay in place, and the third one opens "almost" fullscreen, but shifted a little lower and left.

Tested with borders on.

**Comment by lingtjien** [comment]
Works fine for me...

1. reboot
2. switch to virtual desktop 2
3. open 2 konsole windows
4. switch to virtual deskop 3
5. open 1 konsole window
6. move konsole window to virtual desktop 2

Which settings are you using and could you reset to default configuration and perform these steps?

**Comment by andaag** [comment]
After reinstall + reset this works for me as well, and I can no longer reproduce the issue. Sorry for the noise!
