### ISSUE TITLE
Is there a way to make all windows floating by default except windows from apps in a list?

### ISSUE THREAD

**Issue by tran-simon** [lingtjien/Grid-Tiling-Kwin#87]
Hi

I want to tile only terminal windows and web browsers. Every other window should be floating by default, because I find it annoying when a popup opens tiled and its size is wrong.

Is there a way to do this? thank you

**Comment by lingtjien** [comment]
Currently you can't do that exactly (well you can but very ugly so let's not do that...), but there is a `tile` checkbox in the settings that you can use. If you toggle that off, all clients will start floating and then you can tile whatever client you want after that on demand. Does that suit your need? (if not I could make a small patch)

**Comment by lingtjien** [comment]
Assuming, you found a solution for your workflow

**Comment by tran-simon** [comment]
Can we make floating windows not always-on-top?

**Comment by lingtjien** [comment]
There is currently not a setting for it, I guess I could add that

I added that some time ago because I thought having floating windows behind was not useful, I'm curious why do you not want the floating windows always on top?

**Comment by lingtjien** [comment]
give the dev branch a try

**Comment by tran-simon** [comment]
@lingtjien I'm on the dev branch but don't see an option for it

I find it annoying when there's a floating popup and I would need to look at a tiled window underneath it to find the information required to fill the popup

**Comment by lingtjien** [comment]
I removed the part of the code that made floating windows always on top instead of a toggle. Does it still show as always on top for foating windows?

**Comment by tran-simon** [comment]
Yep it works. Is there a way to define a set of apps that will tile by default? I mainly only want to tile my browser windows and terminal.

**Comment by lingtjien** [comment]
A ignored client name regex that matches everything but your browser and terminal should work for that I believe

**Comment by tran-simon** [comment]
Exactly what i was looking for thank you!
