### ISSUE TITLE
minimize

### ISSUE THREAD

**Issue by jerlockk** [lingtjien/Grid-Tiling-Kwin#9]
By minimizing the windows the grid is not updated and the space remains. Is there a way to fix it?

**Comment by lingtjien** [comment]
That is currently a "feature" depending on how you see it. But I like the suggestion of having the other windows adjust when other windows are minimized

**Comment by ovv** [comment]
Huge :+1: for minimize support.

**Comment by lingtjien** [comment]
Added minimization support in the develop branch, you can check it out there. It needs some testing though and don't have time yet to add it to the README, will come later.

Default:
Meta+M = maximize active client and minimize all others on that virtual desktop
Meta+N = unminimize all clients on current virtual desktop

Change:
refresh shortcut has been moved from Meta+N to Meta+R
