### ISSUE TITLE
Grid Tiling shortcuts not showing up

### ISSUE THREAD

**Issue by MIrlinger** [lingtjien/Grid-Tiling-Kwin#91]
Hello,

I use KDE Plasma on Debian and followed the instructions to install the KWin script. Then successfully added the script in Window Management > KWin Scripts.
I ticked the box and even rebooted my laptop. But when I go to Global Keyboards Shortcuts > KWin, no Grid Tiling shortcuts are showing up. 
Did I miss a step ?

Thanks in advance.

**Comment by lingtjien** [comment]
Which version of KWin are you using?

**Comment by MIrlinger** [comment]
5.14.5

**Comment by lingtjien** [comment]
try the <5.18 branch

**Comment by MIrlinger** [comment]
I'm kinda new with this.
How do I install a newer version of KWin?
I got the latest release from github but I'm not sure how to install in order for it to be used in place of my 5.14 version
Could you guide me please?

**Comment by lingtjien** [comment]
I mean, there is kwin in debian sid at 5.19 (https://packages.debian.org/sid/kwin-x11) so you could try that, but why don't you try the `<5.18` branch first `git checkout <5.18`?

**Comment by MIrlinger** [comment]
Oh ok, I'm not on Debian Sid, so when I try to update kwin-x11, it tells me I already got the newest version.
I'll try migrating to it
Thank you again!
