### ISSUE TITLE
Moving window to another screen reverts window to original screen

### ISSUE THREAD

**Issue by andrei-pavel** [lingtjien/Grid-Tiling-Kwin#93]
I want to kindly report the same behavior as in https://github.com/lingtjien/Grid-Tiling-Kwin/issues/78#issuecomment-734497207. The way I move it is through drag & drop. Was fixed at the time, but got bugged sometime during the latest commits, my guess would be 210944c32be27143666e8683fa321444b672a22f, but not sure. If this keeps coming up, it might mean that it's conflicting with another feature, eh?

**Comment by lingtjien** [comment]
Yeah my bad, delay made the screen variable read after a reset. Try the dev branch

**Comment by andrei-pavel** [comment]
Branch develop (0afdd6792bfaa3e40b12d0e1081b4707b0fb1f9f for posterity) works. Thank you very much! :beers:
