### ISSUE TITLE
Interfering with Screen Edges settings

### ISSUE THREAD

**Issue by jazz-it** [lingtjien/Grid-Tiling-Kwin#94]
1. Try to open at least two windows with similar custom `Window rules` as below:

![](https://i.imgur.com/ylMARCj.png)

2. Then in another workspace, open the `System settings`.

3. Try to go back and forth and apply **different** settings each time (marked with **3**):

![](https://i.imgur.com/sgG8QkN.png)

4. Close the `System Settings` window and try to navigate through your workspaces to observe the behavior of your open windows.

Additional info:
In step 3, instead of always just using the "Apply" button below, try to randomly change the state of the `Screen Edges` settings and click on e.g. `Activities`. When a popup appears, then click "Apply".

Observed behavior:
- Sometimes the `System settings` window freezes and becomes completely unresponsive, until it crashes.
- Sometimes already opened windows (from step 1) change its geometry and the `System Settings` window jumps into their workspace.
- Sometimes when `System settings` window normally closes, the focus jumps to "a random" empty workspace and I couldn't normally use my desktop, until I reboot the system.

Since such system setting may be changed needed very seldom, I would give this bug a low priority.

**Comment by lingtjien** [comment]
And this behavior is observed while this script is active, I assume. What if you disable this script? Are all these things still happening?

**Comment by madjoe** [comment]
> And this behavior is observed while this script is active, I assume. What if you disable this script? Are all these things still happening?

I disabled all my KWin scripts and couldn't reproduce the issue.

**Comment by madjoe** [comment]
Maybe unrelated to this bug, but still may be related to the script:

I reported another issue with "Pager" that does not show up windows with the same set of rules (Force skipping taskbar), but the developer moved the issue to "Rules", which narrows down where the issue may be fixed. For any future reference I'll post the bug report here: https://bugs.kde.org/show_bug.cgi?id=430634

**Comment by lingtjien** [comment]
I guess this one is handled, let me know if you still need help with something
