### ISSUE TITLE
Inkscape won't split

### ISSUE THREAD

**Issue by n-stone** [lingtjien/Grid-Tiling-Kwin#95]
Inkspace won't "split" if I launch a second application. The second application will be moved to the next Desktop, or if a application is already present Inkscape will be moved to the next completely free desktop.

Only Inkspace shows this behaviour and I don't know how to debug this.
Is this also know for other applications?

**Comment by lingtjien** [comment]
Are you using the default settings? (By default inkscape is set to never split, because it's set to a `minSpace` value of `1`, if you don't want that then just remove inkscape from the regex in the settings)

**Comment by n-stone** [comment]
Thanks I wasn't aware of the regex
