### ISSUE TITLE
🐛 freeze when moving window to screen full of windows

### ISSUE THREAD

**Issue by andrei-pavel** [lingtjien/Grid-Tiling-Kwin#96]
Hello!

Steps:
- screen A has full number of windows
- move window from screen B to screen A
- freeze
- mouse can move, and if you were fortunate enough to have last focus on a terminal, cursor sometimes blinks, sometimes doesn't, but you can always type on it even if you don't see the text, just like I did in the demo below
- you can unfreeze with `nohup kwin_x11 --replace &`
- weirdly enough this doesn't work from another tty like `Ctrl + Shift + F2`, command goes through but doesn't unfreeze

Using the latest master 0afdd6792bfaa3e40b12d0e1081b4707b0fb1f9f. Reproduces even when all other kwin scripts were deactivated. Does not reproduce when Grid-Tiling Kwin is disabled. I did try just in case :)

Demo next. Freeze is at 0:10, unfreeze is at 0:20 with blind typing of command.

https://user-images.githubusercontent.com/6838492/103789354-94d84180-5048-11eb-9819-fa0dbc54f06a.mp4

Now I would also be happy with increasing the number of maximum windows on a screen to 3x3, but there's no configure button?

![image](https://user-images.githubusercontent.com/6838492/103789407-a3bef400-5048-11eb-9f6a-cd04ce0e515e.png)

**Comment by lingtjien** [comment]
Thanks for the detailed report (it's actually broken for virtual desktops as well, if your last virtual desktop is full and you try to move something to that one then it gets into an endless loop as well)

**Comment by appleinario** [comment]
I am experiencing a similar problem as well! I had no problems with my previous install of grid-tiling-Kwin on Manjaro KDE last August/September, but my reinstall today showed me this problem. 

Similar case: if the screen is full of windows, for example mine has two, placing the third window would freeze the whole screen.

**Comment by andrei-pavel** [comment]
I've been testing the two commits ever since you committed in develop. They seem to work well. But I just got my first random freeze since then. I've been getting them before too at about the same frequency of one per day, but I thought they were because of windows randomly going to full screens/VDs. But that can no longer be the case. It seems to always happen when I interact with the `telegram-desktop` native app window. Anyways, I'll try to monitor it's behavior.

**Comment by lingtjien** [comment]
Okay, then I'll close this one and if you can find something you can open a new issue
