### ISSUE TITLE
No settings button in KWin scripts settings

### ISSUE THREAD

**Issue by naowalrahman** [lingtjien/Grid-Tiling-Kwin#97]
I wanted to make my grid 3 columns x 2 rows, but when I go to my system settings > window management > KWin scripts, there is no settings button for the "grid-tiling" script. How can this be fixed? 

![image](https://user-images.githubusercontent.com/67881983/106016441-784e8880-608d-11eb-9f38-43b971d5dd7c.png)

**Comment by andrei-pavel** [comment]
Same here, would also like to know.

**Comment by lingtjien** [comment]
Of the 4 normal installation steps, the last 3 are needed to get the settings button. Can you verify that those steps were done correctly? (`ls ~/.local/share/kservices5`)

**Comment by andrei-pavel** [comment]
This helped. My problem was that in the script I use to update all my kwin scripts, I copied over all metadata.desktop to a single file, so they overrode each other. I now have it matched to the repository name and `~/.local/share/kservices5/Grid-Tiling-Kwin.desktop` works for me. Thanks!

**Comment by lingtjien** [comment]
assuming you found the solution
