### ISSUE TITLE
Marktext app not displaying correctly

### ISSUE THREAD

**Issue by blint01** [lingtjien/Grid-Tiling-Kwin#98]
Hi!

First of all, thank you very much for your work. I use your script and love every minute with it. 
After couple months of use, this is the first time I encountered a problem.

I started using MarkText for note taking and with it's default settings it can only display it's initial size. If I want to make it bigger, -for example want to make it fullscreen-, the remaining pixels stay transparent.
Initial size(the whole windows should be black, but the bottom stay transparent): 
![Marktext_1](https://user-images.githubusercontent.com/45589846/108494163-83b95c00-72a7-11eb-8458-9e7ac31c4f25.png)
Fullscreen size(the right side is transparent):
![Marktext_2](https://user-images.githubusercontent.com/45589846/108494431-cd09ab80-72a7-11eb-8e42-589c18e80311.png)

There is a Title bar style settings in the App's preferences. If I set it to native, the fullscreen works and the windows resizing also, but a ugly tool bar appears.
![Marktext_3](https://user-images.githubusercontent.com/45589846/108494677-207bf980-72a8-11eb-8a5e-51d3af48f0ff.png)
Tool bar:
![Marktext_4](https://user-images.githubusercontent.com/45589846/108494928-6afd7600-72a8-11eb-9506-216c02004445.png)

I would like to keep the Title bar settings on custom. Do you have any idea, how could I fix this resizing issue?

**Comment by lingtjien** [comment]
So the border is always the correct size? It's just the content inside that has the wrong dimensions?

(Side note, if you use the global menu widget the toolbar gets placed in there and removed from the application, it's what I use to get a more clean esthetic)

**Comment by blint01** [comment]
Yes, as you can see it here: (with native titlebar)
![Marktext_5](https://user-images.githubusercontent.com/45589846/108719770-4a3f5580-7520-11eb-9103-d3f7d5ab95de.png)

With custom titlebar, the border looks good too, but you can already see the missing parts on the bottom and right side:
![Marktext_6](https://user-images.githubusercontent.com/45589846/108720027-99858600-7520-11eb-8ed0-3dc40fc27d90.png)

**Comment by lingtjien** [comment]
I can't really do anything about that. I can only control the size of the window, which is basically the borders, but what's inside the border is up to the developer of that application.

Seems to me like the custom titlebar option of the application does not correctly resize the content when the window changes size. What happens if you hold the border and drag it along, does the content also resize or does it stay the same size?

**Comment by blint01** [comment]
Alright, I found something.
If I first make it a floating windows(Meta+T), then maximize it, then unfloat it and finally unmaximize it, the content is correctly resizied. No matter what size I make it.
Is it possible to create a script or something, maybe a launch parameter, to do the above commands in order when I open this specific application?

**Comment by lingtjien** [comment]
Could you try to resize the window by dragging the border and see if that fixes the graphical glitch and resizes the content?

To answer your question, I believe you could do that through a simple bash script using `xprop` (assuming you're on X11) and run that script in the `Exec` field of the `.desktop` file.

**Comment by blint01** [comment]
Yes, I tried it, but it didn't work.
The content remains around the same size. 
![Marktext_7png](https://user-images.githubusercontent.com/45589846/109564901-fc0ef100-7ae1-11eb-8e83-9430119faa6a.png)

![Marktext_8](https://user-images.githubusercontent.com/45589846/109564930-0a5d0d00-7ae2-11eb-9588-fc4bda821b4b.png)

If I make the window smaller, than the original size was, it looks like it's nicely fits in the new border size, but actually the content doesn't get resized. :(

**Comment by blint01** [comment]
I was able to come up with a workaround. Not perfect, not nice, but it works. :D

```bash
#!/bin/bash
marktext &
##Wait till the window gets created
until [[ $(xdotool search --class marktext | wc -l) -gt 0 ]]; do
 :
done
sleep 1.5
id=$(xdotool search --class marktext)

##Makes sure the right windows is in focus (selected)
xdotool windowactivate $id
##Fullscreen the window
xdotool key Super_R+w > /dev/null
xdotool windowactivate $id
##Floats the windows
xdotool key Super_R+t > /dev/null
sleep 0.1
xdotool windowactivate $id
##Unfloat
xdotool key Super_R+t > /dev/null
xdotool windowactivate $id
##Unfullscreen
xdotool key Super_R+w > /dev/null
```
The order is important.

Thanks for the help @lingtjien ! Going to continue using your script <3

**Comment by lingtjien** [comment]
> If I make the window smaller, than the original size was, it looks like it's nicely fits in the new border size, but actually the content doesn't get resized. :(

Yikes, guess the application only resizes the content when it's minimized/maximized...

> Thanks for the help @lingtjien ! Going to continue using your script <3

You did the work 👍 I just gave a hint where to look 😄
